### ISSUE TITLE
Document Github Actions & Workflows

### ISSUE THREAD

**Issue by richb-hanover** [PRQL/prql#1036]
I would find it helpful to have a document that describes the expected use of the Actions and Workflows in the `.github` directory. Specifically:

- Which actions/workflows should be run with each push?

- Which are only onecessary prior to a major release of some sort?

I would find this information useful so that I could enable the first kind of checks as I develop in my own private repo, prior to inflicting any of my errors on the maintainers. Thanks.

**Comment by max-sixty** [comment]
Great, thanks for the issue. 

It's maybe too mixed in with lots of other content, or maybe not that clear per se, but WDYT about the content under Tests: https://github.com/prql/prql/blob/main/DEVELOPMENT.md#tests? Maybe we be cleared about which specific workflows run when, rather than just linking to them?

**Comment by richb-hanover** [comment]
I will look at the test descriptions in DEVELOPMENT.md to see whether further action is needed. I'm going to close this and will re-open if I have something else concrete to offer. Thanks.
