### ISSUE TITLE
Add PRQL Version comment to the generated SQL

### ISSUE THREAD

**Issue by snth** [PRQL/prql#1154]
I was wondering whether it might be useful to have a comment like
```sql
-- Generated by PRQL version 0.2.11 (www.prql-lang.org)
```
at the top (or bottom) of the generated SQL?

Maybe in the Playground as well as in `prqlc` with the option to disable / enable it whatever the default ends up being?

That way when you copy and paste SQL to Github issues or dbt models or wherever, you have a reference point where it came from.

If you have Github issues that remain open for a long time, you may not be able to reproduce the output as it was posted in the issue and this would allow you to identify when the behaviour was as described in the report.

---
I also think it could serve as a form of marketing: if someone comes across such SQL code in the wild and they don't know PRQL then they may be prompted to investigate what PRQL is.

**Comment by max-sixty** [comment]
Yes I think this is a nice idea! 

We could implement with an option from the CLI / bindings / header. I'd be fine having it default on if others agree; or we could start with in being opt-in.

It could cause some churn in our examples / tests — the outputs would change every version (or even every commit if we included the exact commit version). But we could turn those off.

**Comment by richb-hanover** [comment]
I am enthusiastic about this idea (appearing at the bottom, I think). A couple more thoughts:

- In another life, I found it helpful to include a date and time in the result to make it easier to compare results. It might be useful here, although I could be convinced otherwise.
   ```
   -- Generated by PRQL version 0.2.11 (www.prql-lang.org) on <some kind of date/time>
   ```
- I hate options. (That is, I'm intensely wary of "just adding another option".) They complicate testing, especially if we're adding the option to avoid churn in our tests. I would support a "no version" option if we made a solemn pledge not to hang any other behavior on it, and to avoid other willy-nilly options. 

Thanks

**Comment by snth** [comment]
I think the date would be a good addition.

Regarding the tests, you could replace the snapshot test calls with a custom function or macro which either strips out comment lines or has some template replacement logic for the version number.

**Comment by aljazerzen** [comment]
:+1: from me. I think it should:
- be at the end, if it is logged by the database, it doesn't take over the log line,
- be enabled by default,
- have an option to be disabled so we can disable it in tests,
- not contain date/time because it makes compilation process non-reproducible (I don't have strong opinion on this one).

**Comment by richb-hanover** [comment]
If it's possible to incorporate @snth's suggestion of stripping/grepping out comments before running tests, it could be in a comment. 

* I agree it should be placed after the emitted SQL
* I can't think of anything else to include besides the version and date/time stamp  
* We can thus avoid the need for an option, and remove the requirement to test it for proper operation

**Comment by snth** [comment]
Also see how this relates to #410 .

**Comment by richb-hanover** [comment]
1. I am so pleased to see this!
2. What do you think about the notion of adding a date/time stamp? As I look at the output in the Playground, I think I would place it on a second comment line
3. Please add it to https://github.com/prql/prql/pull/1311 when that PR gets merged

**Comment by aljazerzen** [comment]
As I wrote, I'm -0.5 on timestamp, but if you have a sound reason for the timestamp, it can easily be added.

**Comment by richb-hanover** [comment]
OK. The timestamp does become less interesting as the language settles down. I can definitely live without it. Thanks.
