### ISSUE TITLE
How to use Table Aliases?

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#1253]
[Moving from discussion, looks like a surprising bug, thank you @richb-hanover ]
### Discussed in https://github.com/prql/prql/discussions/1252

<div type='discussions-op-text'>

<sup>Originally posted by **richb-hanover** December 11, 2022</sup>
I would like to use (I think they're called) Table Aliases to simplify code. That is, I would like to use:

```
from l=TableA
join r=TableB [==Col1]
select [
  l.Col1,
  r.Col1,
]
filter [l.Col1 != r.Col1]
```

* If I use this form, the Playground gives an error: `Unknown name l.Col1` in the filter expression.

* If I move the filter between the `join` and `select`, I get a long `Cannot lower to IR expr:...` message.

What am I missing? Thanks.</div>

**Comment by max-sixty** [comment]
This looks like a bug; surprisingly quite a big one. Thanks for finding it @richb-hanover .

Adding the `filter` here gives a long error:

```elm
from a
join b [a.id == b.id]
filter [b.id == 5]   # works without this
```

```
"Cannot lower to IR expr: `Expr { id: None, kind: List([Expr { id: Some(15), kind: Binary { left: Expr { id: 
Some(16), kind: Ident(Ident { path: [\"_frame\", \"b\"], name: \"id\" }), span: Some(span-chars-38-43), 
target_id: Some(11), ty: Some(infer), needs_window: false, alias: None }, op: Eq, right: Expr { id: Some(17), 
kind: Literal(Integer(5)), span: Some(span-chars-46-47), target_id: None, ty: Some(integer), needs_window: 
false, alias: None } }, span: Some(span-chars-38-47), target_id: None, ty: Some(bool), needs_window: false, 
alias: None }]), span: Some(span-chars-37-48), target_id: None, ty: None, needs_window: false, alias: None 
}`"
```

(line breaks added)

**Comment by richb-hanover** [comment]
> This looks like a bug; surprisingly quite a big one...

Sometimes I feel like Inigo Montoya wandering around with my eyes closed, coming up with interesting stuff...

**Comment by aljazerzen** [comment]
This is indeed a bug, but the original question has an interesting answer:

> If I use this form, the Playground gives an error: Unknown name l.Col1 in the filter expression.

If I add frame annotations, this will make it clear:

```
from l=TableA           # [l.*]
join r=TableB [==Col1]  # [l.*, l.Col1, r.*, r.Col1]
select [l.Col1, r.Col1] # [Col1, Col1]
```
... when applying `select`, table prefixes get removed.

This is currently an implementation consequence, but it can be changed. We need to decide if this is what we want.

**Comment by richb-hanover** [comment]
@aljazerzen   Hmmm... I still see errors in Playground:

```
from l=TableA
join r=TableB [==Col1]
select [
  l.Col1,
  r.Col1,
]
filter [l.Col1 != r.Col1]
```
gives 
```
 7 │ filter [l.Col1 != r.Col1]
   ·         ───┬───  
   ·            ╰───── Unknown name l.`Col1`
```

------------
While 

```
from l=TableA
join r=TableB [==Col1]
filter [l.Col1 != r.Col1]       # move "filter" between join and select
select [
  l.Col1,
  r.Col1,
]
```
gives
```
3 │ filter [l.Col1 != r.Col1]
   ·        ─────────┬────────  
   ·                 ╰────────── function std.filter, param `condition` expected type `bool`, but found type `list`
───╯
```

**Comment by aljazerzen** [comment]
Exactly. 

First error is here because `select` replaces names in scope from `[l.*, l.Col1, r.*, r.Col1]` with `[Col1, Col1]`. This means that after select, you cannot use `l.Col1`, but just `Col1`. In your case, `Col1` is now duplicated, which means you cannot reference both columns. Consider renaming the columns.

As I said, this behavior has not yet been decided upon and is open to discussion.

----

Second error is has been added by my PR and basically which says: "you cannot use list for filter". I should also add a hint: "use `and` instead".

**Comment by richb-hanover** [comment]
Second Error: Ahah! My fault - I just got "in the habit" of wrapping those things at the end of a line in `[ ... ]`. Using paren's (or nothing) works fine. (And the "Don't use a list" hint would be sufficient and specific enough to be in the documentation.)

First Error: Are you suggesting I rename columns in the underlying DB? That would be difficult in the case where I inherit an externally-created DB. Or do I misunderstand your advice? Thanks.

**Comment by aljazerzen** [comment]
Yeah, errors have room for improvement. 

This behavior is discussed at #788

-----

>  Are you suggesting I rename columns in the underlying DB?

No, no, I just mean:

```elm
from l=TableA
join r=TableB [==Col1]
select [
  left = l.Col1,
  right = r.Col1,
]
filter left != right
```

**Comment by richb-hanover** [comment]
Ahah! Yes - you're suggesting assigning names to `l.Col1` and `r.Col1`, then filtering on those assigned names. That works (and makes sense).

I wish there were a better/more specific error message for the first case (instead of simply `` Unknown name l.`Col1` ``) that could go into the documentation to explain this to the next Poor Joe who runs into it. 

And if I may attempt a layman's description of the cause: the "select" 'clears out' the `l` and `r` table aliases, so they're not available for subsequent steps of the pipeline. I wonder if that provides a basis for an improved error message...

**Comment by aljazerzen** [comment]
That's a good description. It should at least go into the docs and i'll try to add a hint. But i doubt it'll be simple enough to be worth it.
