### ISSUE TITLE
How about to reconsider `sort -age`

### ISSUE THREAD

**Issue by linux-china** [PRQL/prql#1472]
From the book:

> When using prefixes, even a single column needs to be in a list or parentheses. (Otherwise, sort -foo is parsed as a subtraction between sort and foo.)

But for junior guys or guys who don't want to read documents, and `from employees | sort -age` is normal requirement :)

**Comment by max-sixty** [comment]
I definitely agree. But unfortunately I don't think there's a good way around it.

The only solution I can imagine[^1] is:
- force whitespace for binary operators, so that `foo -bar` isn't valid as a math operation; only `foo - bar`
- then `sort -age` would be parsed as `sort` and `-age` rather than `sort`, `-` & `age`
- But then we introduce confusion when someone writes `5 -2` instead of `5 - 2` — probably more confusion?

Very open to other ideas! (though we should be wary to have a special case for `sort`, I think that will likely lead to more confusion in the future)

The thing we can do is make a much better error message. We can even have a special error message for `sort` — so if someone does `sort -age` then the error literally says "You probably want `sort (-age)!`.

[^1]: I've seen discussion on this in other languages, but I don't think any have implemented it

**Comment by richb-hanover** [comment]
> When using prefixes, even a single column needs to be in _a list_ or parentheses...

That might be a way out. If someone has to type punctuation anyway (a parenthesis or a bracket), simplify the grammar so that `sort` always requires a list. And when the compiler encounters `sort -foo`, it can emit a hint, like `sort takes a list`.

**Comment by max-sixty** [comment]
> simplify the grammar so that `sort` always requires a list.

Tbc — we can produce the nice error message without sort requiring a list — anytime we find a `sort` & `-` & `X`, then we know we hit this. (someone has to do the work to change the error message in the resolver ofc)

The thing we can't do is have this information in the _parser_, because the [parser](https://github.com/prql/prql/blob/621c1634cabd472e6ae3ce46a0d3f7fa441ca1db/prql-compiler/src/prql.pest#L18) doesn't know about `sort` — it's just looking at words. So it'll always parse `sort -X` into something nonsensical.

A reasonable question would be — can't we just change the parse tree to the correct thing in the resolver? But that's quite difficult + can cause more problems, happy to explain more if helpful.

**Comment by snth** [comment]
> force whitespace for binary operators, so that foo -bar isn't valid as a math operation; only foo - bar

I think we should consider this because then we could also allow [kebab-case](https://en.wiktionary.org/wiki/kebab_case) identifier names. 

I personally don't have any strong feelings on this and am fine with [snake_case](https://en.wikipedia.org/wiki/Snake_case) but people in this [HN thread: Microfeatures I'd like to see in more languages](https://news.ycombinator.com/item?id=34266078) seem to think that kebab-case is a nice microfeature for a language to have.

**Comment by max-sixty** [comment]
> I personally don't have any strong feelings on this and am fine with [snake_case](https://en.wikipedia.org/wiki/Snake_case) but people in this [HN thread: Microfeatures I'd like to see in more languages](https://news.ycombinator.com/item?id=34266078) seem to think that kebab-case is a nice microfeature for a language to have.

I think it's a cool idea. But it's so alien relative to what's out there, (is there _any_ language which requires spaces between operators?) and so central to how people think about symbolic notation, that I don't think it's viable in PRQL. 

I would be a strong vote against requiring spaces, until we can point to an example of it working well elsewhere.

And there are other ways of solving this problem; e.g. improving the error messages.

**Comment by richb-hanover** [comment]
I acknowledge the tension here: it's very appealing for examples to show:

`from foo | sort -bar`

It looks tidy, and simple to use. But... if we need another sort column, syntax suddenly muscles its way in, and the statement turns into:

`from foo | sort [ -bar, baz ]`

A couple observations:

1. From a language standpoint, I'm looking to minimize the number of constructs a new person needs to learn. So I wonder if we should create the rule: Since `sort` sometimes needs a list `[ ... ]`, then just require it.

2. Maybe a tangent. As I began to write up this response, I realized that PRQL has a couple kinds of "clumping together" notation, and that I was only beginning to understand the rules:

* `[ ... ]` is (almost?) always a list of column names, used in `select`, `derive`, `aggregate`, `sort`. 
* `( ... )` for `filter`, `group`, and expressions. It's listed as "Precedence" in the Syntax page, although I'm not sure why `group` has to use it. (Perhaps to keep `{ ... }` in reserve for the time we might need it...)
* `join` is odd man out. Since it takes an expression perhaps it should be wrapped in `( ... )` 

If `sort` always takes an explicit list, newcomers won't be surprised, and we dismiss the concerns about `-age`. Thanks for listening.

**Comment by max-sixty** [comment]
> If `sort` always takes an explicit list, newcomers won't be surprised, and we dismiss the concerns about `-age`. Thanks for listening.

I think this is a valid point. We could move to everything that takes a list requiring a list; it means we can't have `select x = 5` or `derive gross = net + margin`, which are nice though.

I'm going to write up the current semantics more clearly (ref this [todo](https://github.com/prql/prql/blob/main/book/src/queries/syntax.md?plain=1#L99)), including when parentheses are required, then we should think about the clearest approach.

**Comment by richb-hanover** [comment]
> ... it means we can't have select x = 5 or derive gross = net + margin, which are nice though.

It's nice, but a one-column `select` is somewhat uncommon. A one-column `derive` is less so... That's the tension I was speaking of in my earlier post. Trying to balance minimal examples against minimal "rules to learn". I look forward to your writeup

**Comment by max-sixty** [comment]
FYI the docs merged earlier: https://github.com/PRQL/prql/pull/1486 & #1483

If something is unclear in the docs, then please critique away — I don't think they're great but not immediately clear on how to improve them; the complication comes from the language being too complicated here.

If folks have ideas for making the language simpler, that's very welcome. Though it is a complicated issue — please take the time to consider the tradeoffs across the language.

I'll leave this open for a while so we can continue the momentum from this issue.
