### ISSUE TITLE
concat not working in prql-python, producing wrong sqlite syntax in playground

### ISSUE THREAD

**Issue by marvinbernhardt** [PRQL/prql#1473]
With this input 
```
prql target:sql.sqlite

table foo1 = (
    from bar
    take 3
)

table foo2 = (
    from baz
    take 3
)

from foo1
concat foo2
```
I get  this output from playground
```sql
WITH foo1 AS (
  SELECT
    *
  FROM
    bar
  LIMIT
    3
), foo2 AS (
  SELECT
    *
  FROM
    baz
  LIMIT
    3
) (
  SELECT
    *
  FROM
    foo1
)
UNION
ALL
SELECT
  *
FROM
  foo2

-- Generated by PRQL compiler version 0.3.1 (https://prql-lang.org)
```
which sqlite3 does not accept (I think because of the extra brackets around the select statement).

In python, I get 
```
Traceback (most recent call last):

  File ~/offline-hdd/miniconda3/envs/main/lib/python3.11/site-packages/IPython/core/interactiveshell.py:3433 in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  Cell In[80], line 1
    prql.to_sql("""

  File <string>
SyntaxError: Error { span: Some(span-chars-119-125), reason: Simple("Unknown name concat"), help: None }
```

**Comment by aljazerzen** [comment]
Thanks for reporting!

The problem with SQLite will be a pain in the ass. It is not SQLite specific, Postgres is just more lean on what syntax it allows.

For anyone interested in compiler: basically, [this](https://www.sqlite.org/syntax/select-stmt.html) is the structure of select statements in SQL. Note that LIMIT, ORDER and OFFSET come after UNION. One could say that SQL `QUERY = SELECT + (UNION + SELECT)* + ORDER BY + LIMIT`.    And because our code is written to assume that an atomic SQL SELECT can contain LIMIT, ORDER and OFFSET, we translate the atomic select into QUERY and not into SELECT. To squeeze this into UNION, i've used the fact that (QUERY) also qualifies as SELECT - but this apparently only holds for PostgreSQL.

Solution is to instead use this: SELECT * FROM (QUERY) t also qualifies as SELECT. Which means that original query should translate to:
```sql
WITH foo1 AS (...),
     foo2 as (...)
SELECT * FROM (SELECT * FROM foo1) table_0
UNION
SELECT * FROM foo2
```

---

The python problem is caused by the fact that Playground and book contain unreleased versions of PRQL, while python is on 0.3.1.

**Comment by marvinbernhardt** [comment]
Very interesting, thank you for the quick reply.
So just that I get it right: The SQL in my original post without the brackets would be correct SQL. But that only works until an `ORDER BY` or `LIMIT` are used before `UNION`, one can wrap it in brackets and PostrgreSQL is satisfied (other dialects too?), but SQLite wants the extra steps you described (is it then "standard-SQL"?).

**Comment by aljazerzen** [comment]
Yes, exactly!

Most of it is implemented here: https://github.com/prql/prql/blob/main/prql-compiler/src/sql/translator.rs#L300-L354
