### ISSUE TITLE
Datetimes and timedeltas

### ISSUE THREAD

**Issue by pbsds** [PRQL/prql#15]
Postgres has a lot of types, with arithmetic behavior that makes sense. Should PRQL support a way to express datetimes and timedeltas?

Postgres example:
```sql
SELECT * FROM table
  WHERE date > now() - 2 * INTERVAL '1 year';
```

**Comment by max-sixty** [comment]
Yes, I think these functions would be welcome, which can transpile into the equivalent SQL functions. Very open to proposals for these functions.

My overall vision for types is to eventually allow them to be inferred, to help with auto-completion and transpile-time error-checking. But some of that would require knowing the schema of the underlying table, which is much more work than a simple transpiler. 

I'm currently thinking types would be purely inferred rather than specified, given the focus of PRQL on analytical queries, but open-minded if we later find that that's insufficient.

(thanks to @clifton for the ideas around types!)

**Comment by max-sixty** [comment]
@pbsds if you want to draft any datetime functions in an example, please feel free. I'll close this issue since I think I answered the broader typing question, and added a bullet to https://github.com/max-sixty/prql/pull/19

Thank you again for your questions!
