### ISSUE TITLE
Grouping by column derived from switch function generates invalid SQL

### ISSUE THREAD

**Issue by mihkelambre** [PRQL/prql#1564]
Repoducable in playground.
```
# from playground
from tracks
select [
  avg_length = average milliseconds,
  length = milliseconds,
  category = switch [
    length > avg_length -> 'long',
    true -> 'short'
  ]
]
group [category] (
  aggregate (
    count
  )
)
```
Grouping by a column derived from switch function (**that uses window functions**) generates SQL that with window functions in group by.
```
SELECT
  CASE
    WHEN milliseconds > AVG(milliseconds) OVER () THEN 'long'
    ELSE 'short'
  END AS category,
  COUNT(*)
FROM
  tracks
GROUP BY
  CASE
    WHEN milliseconds > AVG(milliseconds) OVER () THEN 'long'
    ELSE 'short'
  END

-- Generated by PRQL compiler version 0.4.0 (https://prql-lang.org)
```

Error thrown:
```
ERROR:  window functions are not allowed in GROUP BY
````

**Comment by max-sixty** [comment]
Thanks a lot @mihkelambre , indeed a bug...

Here's a slightly smaller repro

```elm
# from playground
from tracks
select [
  category = switch [
    length > avg_length -> 'long'
  ]
]
group [category] (
  aggregate (count)
)
```

```sql
SELECT
  CASE
    WHEN length > avg_length THEN 'long'
    ELSE NULL
  END AS category,
  COUNT(*)
FROM
  tracks
GROUP BY
  CASE
    WHEN length > avg_length THEN 'long'
    ELSE NULL
  END
```

Interestingly if there's a function rather than a `switch` then it does use the variable name — here `avg_length`.

```elm
# from playground
from tracks
select avg_length = (average milliseconds)
group [avg_length] (
  aggregate count
)
```

```sql
WITH table_1 AS (
  SELECT
    AVG(milliseconds) OVER () AS avg_length,
    milliseconds
  FROM
    tracks
)
SELECT
  avg_length,
  COUNT(*)
FROM
  table_1
GROUP BY
  avg_length
```

**Comment by snth** [comment]
@max-sixty Your first example fails for a different reason:

    Error: Binder Error: Referenced column "length" not found in FROM clause!

which seems accurate as `length` hasn't been defined in that example.

---
The problem seems to be that with the `switch` it doesn't recognise that it needs to generate the `table_1` CTE for the GROUP BY.

I'm curious why in the second example it includes `milliseconds` as a column in the CTE when it's not needed? @aljazerzen ?

**Comment by max-sixty** [comment]
> @max-sixty Your first example fails for a different reason:
> 
> ```
> Error: Binder Error: Referenced column "length" not found in FROM clause!
> ```
> 
> which seems accurate as `length` hasn't been defined in that example.

I don't get this error... Do you get that in the playground?

**Comment by snth** [comment]
Yes. Might be in the output.arrow tab. On mobile rn.

**Comment by aljazerzen** [comment]
I like these type of bugs, where we already have a framework for solving them.

If the issue with `length` persist, feel free to reopen.

**Comment by snth** [comment]
The following is a minimal example which has the same semantics as the first example and still works in output.arrow:

```elm
from tracks
    select category = switch [
        milliseconds > (avg milliseconds) -> 'long'
    ]
group category (aggregate count)
```

**Comment by max-sixty** [comment]
What's the logic for the extra arrow type? That functions and switch expression are sufficiently different and so should have different syntax?

I'm keen on less different syntax, so I think we should need good reasons

**Comment by max-sixty** [comment]
What's the logic for the extra arrow type? 

That functions and switch expression are sufficiently different and so should have different syntax?

I think we should have as little different syntax as possible, as long as it's not ambiguous — so we should need good reasons for adding a type of syntax. 

For example, we use `sort [-col]`, not `sort [\col]`, because we already have a minus sign, and it's sufficiently clear, even though not quite as clear as the downward sloped slash would be.
