### ISSUE TITLE
Test examples on website

### ISSUE THREAD

**Issue by eitsupi** [PRQL/prql#1593]
The following query, which appears on the top page of the website, will cause an error with the latest prql-compiler.

https://github.com/PRQL/prql/blob/18524c343bd1e8e39399e26a7747c8ffc4e60a67/website/content/_index.md?plain=1#L234-L249

Perhaps files that have been tested externally need to be imported here?

**Comment by max-sixty** [comment]
Thanks for the spot @eitsupi .

I fixed that example. I agree these could be parsed and tested, possibly in a similar way to how we do this for the book.

If it's OK, I'll change the title of the issue to one about testing and leave it open. 

If anyone wants a modest issue to work on without much complex rust, this could be a good one — parse the YAML file, extract the PRQL, check it compiles — then that would be very welcome.

**Comment by nkicg6** [comment]
@max-sixty I took a very rough swing at this using string comparisons and println! debugging (still a WIP, haven't written the actual tests yet) to get an idea of the current status and how it could work. You can find it in my fork under the [website branch](https://github.com/nkicg6/prql/tree/website/website/website-tests).

The results I got were:
```
Passed: 4, Failed: 8
```

Just looking through the failures, some were stylistic and could be fixed by editing the expected SQL, for example the `orthogonal` test:
```
Failed on ID: 'orthogonal'
Expected: SELECT country, MAX(salary) AS max_salary FROM employees WHERE start_date > DATE '2021-01-01' GROUP BY country HAVING MAX(salary) > 100_000
Got:      SELECT country, MAX(salary) AS max_salary FROM employees WHERE start_date > DATE '2021-01-01' GROUP BY country HAVING MAX(salary) > 100000
```
will pass if you drop the stylistic `_` from the SQL. 

Others look like they might be a SQL style difference, and one caused a prql_compiler::compile error (`s-string`). A few questions:
1. What SQL dialect should we use to check the output? For these tests I didn't pass a dialect, but it might make sense to specify one for reproducibility. 
2. How do you want to handle stylistic differences (e.g., `orthogonal`) do we change the expected SQL if it is equivalent?
3. How do you envision this running? To get started I made a new binary in the website directory, but I think it makes more sense to have it as a library in that directory and write tests that run with `cargo tests`. But should we add it to run before the website build in the taskfile, or add it to the website CI... thoughts?

Happy for any feedback or advice here, let me know if I'm on the right track.

**Comment by max-sixty** [comment]
> will pass if you drop the stylistic `_` from the SQL.

Good find! In most dialects that actually wasn't valid; I guess I did a find-replace and missed that one of the hits was the SQL output...

> What SQL dialect should we use to check the output? For these tests I didn't pass a dialect, but it might make sense to specify one for reproducibility.

I think they should just be the generic dialect; that's the SQL that the PRQL produces without a specified dialect

> How do you want to handle stylistic differences (e.g., `orthogonal`) do we change the expected SQL if it is equivalent?

Yes, we can change the SQL. I don't think it's necessary to do the auto-replace in the test, it's going to change very rarely. If you're OK copy & pasting the current errors manually one time.

> How do you envision this running? To get started I made a new binary in the website directory, but I think it makes more sense to have it as a library in that directory and write tests that run with `cargo tests`. But should we add it to run before the website build in the taskfile, or add it to the website CI... thoughts?

What language would you like to use? 

If rust, we could put the code in our `prql-compiler` integration test: https://github.com/PRQL/prql/blob/6c5af7a6dcf84b6dd690e85d4cfcf8d4b84f8a7b/prql-compiler/tests/integration/main.rs. That would reference code outside of the crate, but that's probably OK. 
The book would be another option, or another crate, though adding a whole crate for this might be overkill). We can change the location quite easily later.

If JS, it could go in the playground tests.

---

Thanks, this is going to be useful! It's already caught one issue...

**Comment by nkicg6** [comment]
Ok great! I wrote a small crate to do it, but I'm better with python so I'll add the test to `prql-python` first and if we decide it'd be easier to have it run with the Rust prql-compiler integration tests, I can add the rust tests there too. Here are the mismatches, so we can decide which differences should be edited in the website "expected SQL" and which may be problematic:

Seems to be a syntax difference for `friendly-syntax`
```
Failed on friendly-syntax
Expected: SELECT order.* FROM order WHERE status = 'done' ORDER BY amount DESC
Got:      SELECT * FROM "order" WHERE status = 'done' ORDER BY amount DESC
```
Differences on `windows`
```
Failed on windows
Expected: SELECT employees.*, SUM(paycheck) OVER ( PARTITION BY employee_id ORDER BY month ROWS BETWEEN 11 PRECEDING AND CURRENT ROW ) AS trail_12_m_comp FROM employees
Got:      SELECT *, SUM(paycheck) OVER ( PARTITION BY employee_id ORDER BY month ROWS BETWEEN 11 PRECEDING AND CURRENT ROW ) AS trail_12_m_comp FROM employees
```

`functions` is totally different. I suspect this is an **integer division problem**, where the 9/5 is executed as integer division during processing rather than passing through

```
Failed on functions
Expected: SELECT temp_c * 9/5 + 32 AS temp_f FROM weather
Got:      SELECT temp_c * 1 + 32 AS temp_f FROM weather
```

`top-n` is... different 
```
Failed on top-n
Expected: WITH table_0 AS ( SELECT employees.*, ROW_NUMBER() OVER ( PARTITION BY role ORDER BY join_date ) AS _rn FROM employees ) SELECT table_0.* FROM table_0 WHERE _rn <= 1
Got:      WITH table_1 AS ( SELECT *, ROW_NUMBER() OVER ( PARTITION BY role ORDER BY join_date ) AS _expr_0 FROM employees ) SELECT * FROM table_1 WHERE _expr_0 <= 1
```
`s-string` causes a PRQL compiler error

```
expected pipeline that resolves to a table, but found `<closure over `null` with 1/2 args>` on problem ID: s-string
```

`null-handling` is also quite different
```
Failed on null-handling
Expected: SELECT users.*, COALESCE(channel, 'unknown') AS channel FROM users WHERE last_login IS NOT NULL AND deleted_at IS NULL
Got:      SELECT *, COALESCE(channel, 'unknown') AS channel FROM users WHERE last_login IS NOT NULL AND deleted_at IS NULL
```
`dialects` also causes a PRQL compiler error:

```
Failed on dialects
Error: Binder Error: Referenced column "age" not found in FROM clause!
Candidate bindings: "employees.fax", "employees.state", "employees.city", "employees.email", "employees.phone"
LINE 6:   age
```

**Comment by max-sixty** [comment]
> Ok great! I wrote a small crate to do it,

To the extent it's already mostly working in rust — I would think going with the rust would be ideal; it is slightly more coherent with the rest of the library if we can keep it in rust.

If it's not working or development is slow, then rewriting in python is totally fine!

---

OK, so most of those are small differences in whether the output includes the table name.

`functions` is concerning — I'm very happy we're doing this and worried we hadn't spotted this before.

The others look like a small tweak is needed; e.g. `s-string` needs a `from` above the `derive`. (fwiw I didn't get an error in `dialects`)

**Comment by nkicg6** [comment]
I ended up adding the python tests first, let me know what you think of #1719, I couldn't figure out `s-string` sorry. 
Looks like the CI is working and failed on the tests it was supposed to https://github.com/PRQL/prql/actions/runs/4110255360/jobs/7092892320

I will add the Rust version later this week, I agree Rust is preferred for these tests

**Comment by nkicg6** [comment]
It would be a larger refactor, but it would be nice to have all the PRQL examples (and expected SQL) listed on one place that we can update and test all the language bindings, book, website, etc. from. Might not be practical, but I'll give it some thought as I work through this.

**Comment by max-sixty** [comment]
> It would be a larger refactor, but it would be nice to have all the PRQL examples (and expected SQL) listed on one place that we can update and test all the language bindings, book, website, etc. from. Might not be practical, but I'll give it some thought as I work through this.

Yes I agree. We have a fairly sophisticated (maybe overly sophisticated...) approach to generating the comparisons for the book: https://github.com/PRQL/prql/blob/4cbc78eb4a51c2c841b9d83a0533f3e0230d807a/book/tests/snapshot.rs#L61-L147

So there's a world where we host the showcase items in the book, run that code over them, and then somehow import them into the website. Instead of writing the python tests, we'd get the tests for free but have to write code to put them into a format that Hugo, our website framework, can understand (probably yaml).

But tbh after your PR merges, we're in a pretty good place. The website should stay fairly simple, so I probably wouldn't invest that much in making it super generalized (whereas, say, the playground could benefit from much more investment...)

Thanks @nkicg6 !
