### ISSUE TITLE
Selecting join columns post join appears to be ambiguous

### ISSUE THREAD

**Issue by cottrell** [PRQL/prql#1595]
Selecting join columns post join appears to be ambiguous. 

```prql
from employees
group g (
  sort t
  window expanding:true (
      derive [
      a = sum b
      ]
  )
)
join side:left other [==g]
select [
  g
]
```

```text
Error: 
    ╭─[:12:3]
    │
 12 │   g
    ·   ┬  
    ·   ╰── Ambiguous name. Could be from any of _frame.employees._infer, _frame.other._infer
────╯
```

from -- Generated by PRQL compiler version 0.4.1 (https://prql-lang.org)

Doing `employees.g` solves it but not sure if that is intended (safety) or this is some thing that should be corrected eventually.

**Comment by max-sixty** [comment]
At the moment we've decided to force the explicitness — i.e. `employees.g`, ref https://github.com/PRQL/prql/issues/1503 & https://github.com/PRQL/prql/issues/1193.

Personally I remain a bit unsatisfied by the current ergonomics. But everything is expressible, and I recognize there are benefits to the choices we've made. So I would put this in the category of "OK for the moment, let's see, we'll make it better in the future somehow". 

If anyone has ideas or views that aren't expressed in the linked issues, feel free to add them here.

@cottrell I'll close this but please feel completely free to reopen

**Comment by RalfNorthman** [comment]
I wanted to put a big join in a `let` statement so two different `let`s downstream could use the same join as a starting point. The joined tables have many identical column names (id for example). This makes referring to them (outside the original `let`) trigger the ambiguous name error if I don't rename the columns first.

I'm not sure how I would want a future syntax to handle this, I just want to point out a case where this issue is causing some friction. :-)

I was about to make an example with the music database, but those tables use the convention of  **tablename**_id as id-column so it wouldn't be very illustrative.

EDIT:
Would it be possible (and desirable) to implement something that made this syntax work:
```prql
let joined = (
  from a=table_a
  join b=table_b [a.id == b.table_a_id]
)
from j=joined
select [
  j.a.id,
  j.b.id,
]
```

**Comment by max-sixty** [comment]
That's an interesting case @RalfNorthman .

I really like the idea of a hierarchical namespace for columns, like `j.a.id`.

That said, I'm not sure it maps well to SQL. That's not a death-knell for the feature, but would mean we need to manage the interface carefully. For example — what SQL columns does that return?

Probably the closest concept is using a Struct in the DBs which support it. So in your example there would be a struct `a` & struct `b`, each of which have the same columns, making the hierarchy.

Feel free to expand / adapt the idea; we can reopen this or open a new issue if it has legs
