### ISSUE TITLE
Proper version of mdbook-admonish?

### ISSUE THREAD

**Issue by richb-hanover** [PRQL/prql#1598]
When I build my Dockerfile, I see the following warning about the `mdbook-admonish` version. Is this important? What file(s) need to be changed to sync them up? Thanks.

```
task: [test-rust] cd book && mdbook build
2023-01-21 13:26:57 [INFO] (mdbook::book): Book building has started
Warning: The mdbook-admonish preprocessor was built against version 0.4.21 of mdbook, but we're being called from version 0.4.25
```

**Comment by max-sixty** [comment]
Yes this warning is a bit annoying — but it's actually fine and has no effect. To silence it:

- We could follow the steps on the mdbook-admonish docs to rebuild on the latest version, but it will reappear soon
- We could even add those steps to `test-all` so it runs often
- We could put an issue upstream asking it not to warn on patch releases

I'll close because there isn't an easy way of fixing it permanently, but feel free to take a swing at any of those / reopen if needed.

**Comment by richb-hanover** [comment]
A good resolution. (The original report follows my rule, "We promise not to fix it if we don't know it's broke" :-) Thanks.
