### ISSUE TITLE
Unused snapshot tests?

### ISSUE THREAD

**Issue by eitsupi** [PRQL/prql#1647]
While editing #1646, I noticed that the old syntax was included in the snapshot. But the test does not fail.
I don't understand the structure of the tests for book, perhaps this snapshot can be deleted because these are old files?

https://github.com/PRQL/prql/blob/32981572f136c6c970efef0bb0b349737c51d98f/book/tests/snapshots/snapshot__%40examples__cte-0.prql.snap#L3-L4

**Comment by max-sixty** [comment]
Hmmm, I'll have a look at this. I recently added something to test for unreferenced snapshots, possibly it's not working correctly in this case.

**Comment by max-sixty** [comment]
Ah, this is because of https://github.com/mitsuhiko/insta/issues/336 (and ref https://github.com/PRQL/prql/pull/1456) — we can't force update them by default because of a windows issue.

So the `expression` there is old. Because the SQL didn't change when the PRQL changed, the file wasn't updated, so still has the old value.

We can run a one-off update with `cargo insta --force-update-snapshots` — anyone is always welcome to run this, until the upstream issue is fixed and we can enable it by default.
