### ISSUE TITLE
Add `stable` branch tools

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#1658]
To maintain a stable branch which deploys the book & playground, based on the discussion at https://github.com/PRQL/prql/issues/1507, we need to:
- Add a bot to backport PRs based on a label, like https://github.com/tibdex/backport/blob/main/.github/workflows/backport.yml
- Change the web release to deploy from `stable`
- Update docs in `development.md` with this process

I think that's all, let me know if I missed anything!

**Comment by aljazerzen** [comment]
I did a part of this in #1668. I used branch name `website`, because that seemed more descriptive.

I cherry-picked all commits that changed website/playground/book since 0.4.2 and pushed that to website. Until the bot is setup, we can manually cherry-pick any commits that urgently need to go to the website.

**Comment by max-sixty** [comment]
Ok! Thanks

I would have preferred to gate doing this on the tools & docs — the docs are now wrong — but let's see how we go and if we don't get to those and the cherry picking doesn't keep up, we can reassess.

**Comment by aljazerzen** [comment]
I added some docs about publishing the website. The important bit in the "release" TODO list:

https://github.com/PRQL/prql/blob/9960e8988df3fa23b18810dce6a55debb65e3d4b/book/src/contributing/development.md?plain=1#L369

I wanted to create a GH action that would do this automatically, but it seems like it is not possible, because [github actions cannot bypass branch protection rules](https://github.com/orgs/community/discussions/25305) and I think we would really want to have that enabled on the branch.

**Comment by aljazerzen** [comment]
Ok, I realized that we don't need branch protection rules, because push access to the repo is limited already.

Which means I can add the GH job in the release workflow to force push to `website` branch, which should trigger the publish-web action.

**Comment by max-sixty** [comment]
I think with https://github.com/PRQL/prql/pull/1680 this is now complete!

**Comment by eitsupi** [comment]
I noticed that the target name is not displayed in the footer (implemented by #1731) in the playground.
Could this be related to a particular commit not being pushed to the web branch?

**Comment by aljazerzen** [comment]
Playground does not specify the compile target, so it falls back to `prql target:` header, which does not emitted in the signature. This is intentional, as the header is not a compiler setting, but the content compiler operates with.

**Comment by eitsupi** [comment]
Oh, I see. Thank you for the explanation.
