### ISSUE TITLE
how to make queries prepared ?

### ISSUE THREAD

**Issue by maarekj** [PRQL/prql#1683]
how to make queries prepared ?

**Comment by max-sixty** [comment]
Could you give an example?

**Comment by vanillajonathan** [comment]
[Prepared statements](https://en.wikipedia.org/wiki/Prepared_statement) are used by libraries in order to avoid  [SQL injection](https://en.wikipedia.org/wiki/SQL_injection) attacks.

**Comment by max-sixty** [comment]
We support using parameters: https://prql-lang.org/book/syntax.html#parameters. 

So we don't have particularly deep support here, and rely on the database & its connector to implement much of it. Given that PRQL current target is compiling to SQL, that constraint is fairly fixed at the moment.

I think there's space to do something better here in the long-term. Possibly `prql-query` could be a good place to experiment.

I'll close this since we do have the Parameters support. Making something better probably requires some thought and time for the language to expand, but feel free to comment here with any ideas.

**Comment by maarekj** [comment]
This is exactly what i needed. I had not seen this part in the doc. Sorry.

On the other hand, I have already noticed some bugs with this feature (if you use select, you can no longer use the parameters). I will now create a way out.

**Comment by maarekj** [comment]
https://github.com/PRQL/prql/issues/1827

**Comment by max-sixty** [comment]
Great, I added a reference so searching for "Prepared" will bring it up. We'll work on #1827, good bug report!
