### ISSUE TITLE
Formal definition of operators and implict casting

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#1712]
Found by @nkicg6 in #1593 :

```elm
from weather
select temp_f = temp * (9/5)
```

```sql
SELECT
  temp * 1 AS temp_f
FROM
  weather
```

...I guess this is because we're parsing them as ints and doing int division in the complier?

**Comment by aljazerzen** [comment]
Is this not expected behavior?

`(9/5)` is equivalent to `1` in PRQL, right?

**Comment by max-sixty** [comment]
> `(9/5)` is equivalent to `1` in PRQL, right?

I definitely hadn't thought so!

Are you thinking that `/` should be int division, like python2? Or that we shouldn't silently convert ints to floats?

I think this would be quite unexpected from most users...

**Comment by aljazerzen** [comment]
```
➜  ~ python3.11
Python 3.11.1 (main, Dec  7 2022, 01:11:44) [GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 9/5
1.8
>>> 9//5
1
>>>
➜  ~ node
Welcome to Node.js v19.4.0.
Type ".help" for more information.
> 9/5
1.8
>
➜  ~ echo 'fn main() { println!("{}", 9 / 5); }' > a.rs && rustc a.rs && ./a
1
➜  ~
➜  ~ sqlite3 db.sql "SELECT 9/7"
1
➜  ~ psql -U postgres -d chinook -c "SELECT 9/7"
 ?column?
----------
        1
(1 row)
```

There doesn't seem to be consensus here, so the question is: do we want implicit type conversions?

This should probably be decided in broader context of how we want to define semantics of operators and do we want to support operator overloading?

So I'd suggest we postpone this issue until typing system is decided.

**Comment by nkicg6** [comment]
Interesting, yes Python changed integer division from `/` to `//` in the python2->python3 move to make `/` represent "true" division (see [pep 238](https://peps.python.org/pep-0238/)). This matches the behavior of most dynamic languages in my experience, so most dynamic language users likely "expect" this behavior (see your python and node examples), so I'd suspect most users would be surprised by the prql behavior here despite it being technically correct. 

But databases (postgres and sqlite at least) will default to integer division unless you are explicitly dividing floats. 

```
sqlite> CREATE TABLE weather (temp REAL);
sqlite> INSERT INTO weather (temp) VALUES (20),(25.5),(30);
sqlite> SELECT temp * (9/5) + 32 FROM weather;
# 52.0
# 57.5
# 62.0
```
vs 
```
sqlite> CREATE TABLE weather (temp REAL);
sqlite> INSERT INTO weather (temp) VALUES (20),(25.5),(30);
sqlite> SELECT temp * (9.0/5.0) + 32 FROM weather;
# 68.0
# 77.9
# 86.0
```
A solution may be to just pass the math expression unchanged to the SQL rather than parsing and processing them. I haven't checked other SQL dialects, but that defers the behavior to executing the SQL at least.

**Comment by max-sixty** [comment]
Interesting, I didn't even know that postgres & sqlite did that — I guess I haven't done much work with ints in postgres. In BigQuery, it will implicitly convert to a float.

I do think it's quite surprising that in DBs that do make the conversion, such as BQ, `9/5=1`, but `9/col=1.8` where `col` is a column with `1`.

Maybe PRQL should simplify expressions to rational numbers, as a fraction — i.e. `9/5 * 2` would go to `18/5`. That way we simplify expressions without losing any information?

**Comment by aljazerzen** [comment]
I strongly think that in PRQL `9/5 == 9/col` where `col==5`. If some DBMSs don't work this way, we should find a way to force them to do so.

Right now, we just pass the operator to underlying database, so formal definition of what operator do would be "whatever your databases does". In the long term, we need to define what `9/5` is in PRQL, because that is the thing that is causing SQL dialects to be incompatible with each other.

## Framework

We should approach this systematically. Let's talk about types that these operators take and produce, which is a good indicator of what they do:

```
<float> / <float> -> <float>
<int>   / <int>   -> <?>     # this here is the question
```

## Option 1: implicit casting

This is what dynamic languages do: convert to float before dividing.

This means that PRQL can have only one implementation of `/` operator, but we may need another symbol for integer division.

## Option 2: operator overloading

Let's define multiple operators for each type:

```
<float32> / <float32> -> <float32>
<float64> / <float64> -> <float64>
<int32> / <int32> -> <?>
<int64> / <int64> -> <?>
```

For this we would need a way to define multiple implementations for operators, but it would open a door to also allow this:

```
<string> + <string> -> <string>
```

---

PS: I don't have the bandwidth to do good language design right now, so I'll try to refrain from giving out opinions without much thought.

**Comment by max-sixty** [comment]
I very much agree with the framework & that those are the tradeoffs.

If we want to get this to work soon, though:

> I strongly think that in PRQL `9/5 == 9/col` where `col==5`. If some DBMSs don't work this way, we should find a way to force them to do so.

...what do you think about not executing `/` in PRQL for the moment?

So we'd calculate the other operators, except for division. 

(Possibly that would look like having fractions as an atom in the lang, possibly that actually complicates the description)

**Comment by aljazerzen** [comment]
Sure.

**Comment by eitsupi** [comment]
Rustic question: why does the PRQL handle these operations?
I think the compiler will compute these fast enough, but I feel it is more likely that it is more intuitive to leave it up to the computation engine behind it.

**Comment by aljazerzen** [comment]
Because it may lead to much more simplified results:

```
func get_name full:false -> switch [full -> f"{first_name} {last_name}", true -> first_name]

from sales
select [
  get_name,
  get_name full:true
]
```

Yes, this could all be handled by the database. And yes, this argument does not really apply to division. So this behavior is here mostly because it can :D

**Comment by max-sixty** [comment]
Now that we don't do implicit `/` in PRQL, can we roll this into #2426?
