### ISSUE TITLE
Font files in website

### ISSUE THREAD

**Issue by eitsupi** [PRQL/prql#1713]
It looks like the font files are included in the source code of the website, which is probably not compatible with the Apache-2.0 license.
(As far as I could find, I couldn't even tell if redistribution of this is allowed)

https://github.com/PRQL/prql/blob/7c96513a2144671ca90e6328ac01b0d4f518e427/website/themes/prql-theme/static/fonts/AvenirNext.woff
https://github.com/PRQL/prql/blob/7c96513a2144671ca90e6328ac01b0d4f518e427/website/themes/prql-theme/static/fonts/AvenirNext.woff2

Perhaps we need to remove these from the source code?

**Comment by aljazerzen** [comment]
Yup, that's a problem I haven't thought about.

We can:
- remove files from source code and link to some CDN (I really dislike this),
- use some other opensource font,
- use default fonts that are already installed on people's computers.

**Comment by max-sixty** [comment]
Hmmm, I do think it looks much worse, from https://github.com/PRQL/prql/pull/1721:

<img width="673" alt="image" src="https://user-images.githubusercontent.com/5635139/217419540-c0a267df-c13a-4421-a7fb-865d36d572ed.png">

WDYT about referencing a CDN and then falling back to a default if that's not available?

**Comment by aljazerzen** [comment]
CDNs will always be available - my problem with them is that ...
<details>
<summary>rant</summary>
...they offer little benefit other than convenience, since browsers don't use cached resources cross-site anymore. But by linking to a third-party in our website we are allowing them to collect our visitors data, almost as we would just embed their analytics into our website. This seems just obscurely wrong to me and I would fully support a push to change how browsers interact with third-party domains.
</details>

But if it looks much worse to you, we can pull the font files from [the brand repo](https://github.com/PRQL/prql-brand) during website build process.

Although, looking at the typeface now, I think we don't even have permission to use it, so we may need to choose a new one.

**Comment by max-sixty** [comment]
> But if it looks much worse to you, we can pull the font files from [the brand repo](https://github.com/PRQL/prql-brand) during website build process.
> 
> Although, looking at the typeface now, I think we don't even have permission to use it, so we may need to choose a new one.

I had thought it was OK to have some files in a repo that had a different license (we have https://github.com/PRQL/prql/blob/main/book/src/lib.rs#L1-L3 atm!). So I think you're right that it's a permission issue rather than a license issue.

Maybe we try and find a nice open-source font then...

**Comment by aljazerzen** [comment]
Inter ExtraBold

![image](https://user-images.githubusercontent.com/11072061/217567012-e95d0a23-4ab2-4c17-828a-2747a49e925b.png)


Young Serif

![image](https://user-images.githubusercontent.com/11072061/217567166-abce9939-89be-431a-bb1a-d0e98d82ec81.png)

**Comment by max-sixty** [comment]
> Inter ExtraBold

This looks good! Thanks for finding it...
