### ISSUE TITLE
Can't run `task test-rust-fast`

### ISSUE THREAD

**Issue by eitsupi** [PRQL/prql#1872]
Seems to be an error.

```sh
$ task test-rust-fast
task: [test-rust-fast] cargo insta test --accept -p prql-compiler --lib --target=$(default-target)
"default-target": executable file not found in $PATH
error: target was empty
warning: non snapshot tests failed, not accepted changes
task: Failed to run task "test-rust-fast": exit status 1
```

https://github.com/PRQL/prql/blob/9b21e945282130fea5619d994ff1568b4ea46f0d/Taskfile.yml#L249-L251

**Comment by max-sixty** [comment]
This requires `default-target`, which gets installed with `task setup-dev`, or `cargo install default-target`

**Comment by max-sixty** [comment]
FWIW we do this because otherwise the cache is busted because of supplying the `wasm` target, and not supply any target. By supplying the default target explicitly, the cache isn't busted by RUSTFLAGS changing. (I've been deeper into this than I expected to...)

If anyone else hits this, please reply to this with "me too!" and I'll add an explicit message to the Taskfile when the binary isn't installed
