### ISSUE TITLE
Add a `--format` option to prqlc to produce yaml

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#1912]
Currently `prqlc` only returns JSON:

```
❯ echo "from x" | prqlc resolve
{
  "def": {
    "version": null,
    "other": {}
  },
  "tables": [
    {
...
```

In the playground, we produce YAML, which is arguably more friendly for people (no object-level discussion of whether this claim is accurate please!).

We could allow a `--format` option to `prqlc` to produce this output. Would be a nice contribution, reasonably well modularized while also introducing the main rust code.

**Comment by aljazerzen** [comment]
I had used serde-yaml instead of serde-json, but it had errors saying "serialization into YAML does not yet support nested enums" or something similar.

It's real easy to change though, just change `serde_json` to `serde_yaml` here: https://github.com/PRQL/prql/blob/main/prql-compiler/prqlc/src/cli.rs#L135

It's debug output anyway so I change it from time to time when working on something.
