### ISSUE TITLE
Translate Joins to SQL

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#194]
This will likely require a few PRs:
- Parse into a newly made a Joins struct
- Materialize (easy, nothing special here)
- Translate into SQL (could be a decent effort, e.g. will require thinking about when we need to start a new CTE)
- Decide how to handle default values / corner cases / etc

**Comment by aljazerzen** [comment]
So there is my test case on [employees database](https://github.com/vrajmohan/pgsql-sample-data.git):

> Rank the employee titles according to the average salary for each department.

My solution:

- for each employee, find their average salary,
- join employees with their departments and titles (duplicating employees for each of their titles and departments)
- group by department and title, aggregating average salary 
- join with department to get department name


```SQL
WITH i AS (
  SELECT e.emp_no, AVG(s.salary) AS emp_salary
  FROM employees e
  LEFT JOIN salaries s ON s.emp_no = e.emp_no
  GROUP BY e.emp_no
), j AS (
  SELECT de.dept_no, title, avg(emp_salary) AS avg_salary
  FROM i
  LEFT JOIN titles t ON t.emp_no = i.emp_no
  INNER JOIN dept_emp de ON de.emp_no = i.emp_no
  GROUP BY de.dept_no, t.title
)
SELECT d.dept_name, title, avg_salary
FROM j
LEFT JOIN departments d ON d.dept_no = j.dept_no
```

Rewritten in PRQL:

```elm
from employees
join side:left salaries [salaries.emp_no = employees.emp_no]
aggregate by:[employees.emp_no] [
  emp_salary: average salary
]
join side:left titles [titles.emp_no = emp_no]
join dept_emp [dept_emp.emp_no = emp_no]
aggregate by:[dept_emp.dept_no, titles.title] [
  avg_salary: average emp_salary
]
join side:left departments [departments.dept_no = dept_no]
select [dept_name, title, avg_salary]
```

Which currently compiles to:
```
WITH table_0 AS (
  SELECT
    AVG(salary) AS emp_salary,
    *
  FROM
    employees
    LEFT JOIN salaries ON salaries.emp_no = employees.emp_no
  GROUP BY
    employees.emp_no
),
table_1 AS (
  SELECT
    AVG(AVG(salary)) AS avg_salary,
    *
  FROM
    table_0
    LEFT JOIN titles ON titles.emp_no = emp_no
    JOIN dept_emp ON dept_emp.emp_no = emp_no
  GROUP BY
    dept_emp.dept_no,
    titles.title
),
table_2 AS (
  SELECT
    dept_name,
    title,
    AVG(AVG(salary))
  FROM
    table_1
    LEFT JOIN departments ON departments.dept_no = dept_no
)
SELECT
  *
FROM
  table_2
```

This already mostly works! Although:

1. when using aggregate by, produced select must not have `*` but only grouped-by and aggregated columns (first select should only contain `emp_salary` and `emp_no`). Currently this can be worked around by adding `select [emp_no]`, but I believe that this should be automatically inferred, because there is no other valid way.
2. from the point where alias `emp_salary` is introduced for `average salary`, we should use `emp_salary` instead of the function call. This currently causes problems when declaring `average emp_salary` producing `AVG(AVG(salary))`. This means that we have to introduce "scopes" that encapsulates each of the atomic pipelines.
3. we need table aliases in `join`s and `from`s because `join`s get real long. Also, I think that using only `emp_no` in second select will not resolve to `table_0.emp_no`.

(now writing about this I realized that I would have needed to select from `employees` table at all... I could have only aggregated `salaries` table by `emp_no`. Oh well...)

**Comment by max-sixty** [comment]
Great test case and observations! I agree with all three.

Re the aliases, we could also use `USING` to shorten these, for equi-joins.

Does this mean you've already written the "translator" code for joins too? If so, we can definitely merge it in and resolve your observations in future PRs.

**Comment by aljazerzen** [comment]
I did a "proof of concept" for translator :) It chugs all of the joins from an atomic pipeline to its last from statement.

But materializer is not (i dont know what shoud it even do. Resolve functions?)

So, you can merge then.
