### ISSUE TITLE
Return the compiled query directly in prql-lib?

### ISSUE THREAD

**Issue by zhicwu** [PRQL/prql#2024]
In prql-dotnet library, I noticed the following code, which assumed there's up to 1024 bytes will be returned from compile method. I actually tried the same thing along with pointer in Java using JNA but it didn't work quite well.
https://github.com/PRQL/prql/blob/8daadbe7e080ee726e642f627e2f927421b5b3ea/prql-dotnet/PrqlCompiler/PrqlCompiler.cs#L48-L52

I'm not familiar with C/Rust, but I'm wondering if it's better to change the following
https://github.com/PRQL/prql/blob/8daadbe7e080ee726e642f627e2f927421b5b3ea/prql-lib/libprql_lib.h#L44

to something like below?
```c
const char* compile(const char *prql_query, const struct Options *options, int* exitCode); 
```

**Comment by max-sixty** [comment]
Thanks for the issue @zhicwu .

@vanillajonathan would you have any thoughts? I appreciate anything you could do here to help.

**Comment by vanillajonathan** [comment]
I find FFI a bit tricky, I had to try a lot of things a bunch of times to get it to work, also I don't code in C so I am not really good at that, but what I noticed is that I wasn't able to just pass in a string as parameter, maybe because C doesn't have a a string datatype or just because the FFI in .NET doesn't let you do that, else I would get exceptions or crashes. So I had to use a byte array, and it wouldn't work just an empty byte array, it had to be preallocated.

I also did the PHP library, there I could pass in a string, but it wouldn't work with a empty string either, I had to pre-allocate it too using the [`str_pad`](https://www.php.net/str_pad) to pad it with whitespace.

I don't know what the best practices for FFI are, or if changing the signature to return the compiled query  would make it any easier or harder to deal with. Another thing worth mentioning is that the bindings just returns an error code and does not expose errors.

**Comment by aljazerzen** [comment]
As far as I'm aware of, passing a reference to the buffer to which the output should be written is a standard practice when reading data in C. But usually you also pass max length to read:

```c
void read(char *out, int n);
```

Our case is a bit different, because calling code cannot know the expected result length. Also this is not a stream where you could just call the function iteratively until all the input is read.

So I agree to change the signature to return `char *`.

I can work on that. And also return errors as structs and not just composed strings.

**Comment by max-sixty** [comment]
> Our case is a bit different, because calling code cannot know the expected result length. Also this is not a stream where you could just call the function iteratively until all the input is read.
> 
> So I agree to change the signature to return `char *`.
> 
> I can work on that. And also return errors as structs and not just composed strings.

That would be great, thank you very much, it'll unblock lots of others. Assign me something to reciprocate :)

@vanillajonathan would you be up for updating `prql-php` & `prql-dotnet` if we change the `prql-lib` API?

**Comment by vanillajonathan** [comment]
I guess, if it makes the library better than it needs to be done, admittedly it was a bit painful to get working though, and the PHP `compile` function doesn't work at the moment anyway.
Can someone get the other bindings to work to prove its possible? 😂️

**Comment by zhicwu** [comment]
Thanks @aljazerzen. If we take approach like `void read(char *out, int n)`, we'll likely call the method twice for each query as the first call is to figure out how many characters we'll get.

I'm no expert of this, but I'd suggest to make a minor change in a PR and let @vanillajonathan and I to validate prql-(php|donet|java) before merging into main.

**Comment by aljazerzen** [comment]
I've done the work and decided to put in the extra work and do it the right way. All functions now return:

```c
typedef struct CompileResult {
  const int8_t *output;
  const struct ErrorMessage *errors;
  size_t errors_len;
  size_t errors_capacity;
} CompileResult;

/**
 * An error message.
 *
 * Calling code is responsible for freeing all memory allocated
 * for fields as well as strings.
 */
typedef struct ErrorMessage {
  /**
   * Machine-readable identifier of the error
   */
  const int8_t *const *code;
  /**
   * Plain text of the error
   */
  const int8_t *reason;
  /**
   * A list of suggestions of how to fix the error
   */
  const int8_t *const *hint;
  /**
   * Character offset of error origin within a source file
   */
  const struct Span *span;
  /**
   * Annotated code, containing cause and hints.
   */
  const int8_t *const *display;
  /**
   * Line and column number of error origin within a source file
   */
  const struct SourceLocation *location;
} ErrorMessage;
```

There is a lot of pointers, because `String`s are represented by a pointer to first char and `Option` by a pointer that may be null. So nullable strings are pointers to pointers.

Is this a good design? Does anyone have a better idea? How do people express `Option` without allocating on the heap?

I contemplated representing nullable strings as a single nullable pointer, but it didn't seem consistent with other nullable fields like `span`.

I've also added `result_destroy()` function that frees all the allocated memory

**Comment by vanillajonathan** [comment]
Does that handle multiple error messages?
There's been talk in the VS Code issue #1998 about having support for information and warning messages too.

**Comment by aljazerzen** [comment]
Yes, there may be multiple errors in the `CompileResult` (which contains a pointer to the first one and errors_len).

When we add lints and warnings, we'd probably rename:
- `errors` to `messages` and
- `ErrorMessage` to `Message`.

This opens a question: should we make this change now and make this future-proof?

**Comment by max-sixty** [comment]
> When we add lints and warnings, we'd probably rename:
> 
>     * `errors` to `messages` and
> 
>     * `ErrorMessage` to `Message`.

One issue with this design is that we likely want info and warnings for queries that successfully compile, but we return a sum type, so xors the SQL & the errors...

**Comment by aljazerzen** [comment]
I'm saying that we'd return something like this:
```c
typedef struct CompileResult {
  const int8_t *output;
  const struct Message *messages;
  size_t messages_len;
  size_t messages_capacity;
} CompileResult;
```

... which is a struct that can contain both output and messages.

**Comment by max-sixty** [comment]
> I'm saying that we'd return something like this:

Very much agree!

(out of interest, what's the role of `messages_capacity`?)

---

I would vote to not wait to change the `prql-compiler` API to allow this, but if it's easier to implement this API in `prql-lib` and currently only have messages on a failed result, rather than make the change later, then great.
(and your call obv)

**Comment by aljazerzen** [comment]
> (out of interest, what's the role of `messages_capacity`?)

It's the amount of allocated elements in the messages. This is always greater or equal to `messages_len`, which represents the number of *used* elements. This is all abstracted away by `Vec` in Rust. I need it here, because to free the memory, I'm reconstructing the `Vec` and then dropping it.

But it turns out that when dropping, having only the pointer to first allocated byte is enough to drop all the memory. So `messages_capacity` is not needed actually.

----

Cool, I'll future proof the API then.

**Comment by vanillajonathan** [comment]
It _looks_ good to me but I cannot say whether this is a good design or not because I just don't know. I don't know the best practices for foreign function interface (FFI) and writing portable C code suited for use from other languages.

**Comment by aljazerzen** [comment]
I've updated the prql-php bindings and now only prql-dotnet remains to be done.

**Comment by vanillajonathan** [comment]
@aljazerzen Do you want to update the .NET library or do you want me to do it?

**Comment by aljazerzen** [comment]
Can you do it? I don't want to try setting up a nix shell for dotnet :D

**Comment by vanillajonathan** [comment]
Yeah, I can do it. I'll do it today or tomorrow.

**Comment by max-sixty** [comment]
The final stage was completed in https://github.com/PRQL/prql/pull/2111 — thanks @vanillajonathan !
