### ISSUE TITLE
`deb`, `rpm` & `snap` tasks failing

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#2065]
I think this is probably a small issue, around quoting things: https://github.com/PRQL/prql/actions/runs/4371758464/jobs/7647949921

I had thought we'd tested them, possibly something small changed after we merged

Would be great to fix them, and then to use them to start publishing release assets — then they would be quite useful. If we can't fix them, we should temporarily disable them until then work.

CC @vanillajonathan (I know I copied you on another issue today — hope that's OK — we're very grateful for your contributions and hope they continue!)

**Comment by vanillajonathan** [comment]
Okay I investigated this.

As for the rpm and deb packages the package description (the `desc` field in the YAML file) spans multiple lines. We used the `|` syntax and that didn't work good, I tried to use the `>` syntax which worked better for the rpm package, but still fails on the deb package because they handle string replacement in a slight different way.

See https://yaml-multiline.info/ for a description of various ways for doing multi-line strings in YAML.
I filed a issue with `build-deb-action` at jiro4989/build-deb-action/issues/43.

So maybe we have to shorten the description or have just one really long line without line breaks.

As for the Snap I believe it fails because you have not declared a secret with the name `STORE_LOGIN`. By the way, since we might want to publish this to some other software store, we might want to rename this to `SNAP_STORE_LOGIN` or `SNAPCRAFT_STORE_CREDENTIALS` or something.

**Comment by max-sixty** [comment]
> As for the Snap I believe it fails because you have not declared a secret with the name `STORE_LOGIN`. By the way, since we might want to publish this to some other software store, we might want to rename this to `SNAP_STORE_LOGIN` or `SNAPCRAFT_STORE_CREDENTIALS` or something.

Apologies; I had called it a different name. I've renamed it in #2072

**Comment by max-sixty** [comment]
These failed again, I think the `deb` & `rpm` for the same reasons.

The `snap` failed because it can't find the icon: https://github.com/PRQL/prql/actions/runs/4402023644/jobs/7708766674

Do you know what the correct relative path should be there, now that it's in the `packages` path?

**Comment by vanillajonathan** [comment]
Yes, the `deb` and `rpm` packages failed for the same reason as last time. I described why in the post above. I contacted the developer of the build-deb-action but he hasn't replied yet. We could fix it by changing the description for the `.deb` package from a multi-line description to a single-line description. For the `.rpm` package we can keep the multiline description by changing the YAML syntax from `|` to `>`.

Then Snap package seems to fail because it cannot find the icon. I don't know what the correct relative path would be. The `snap` folder is traditionally in the root. I would try to change the logo path in the `snapcraft.yaml` file from `../web/` to `../../web`.

Edit: I got a reply at jiro4989/build-deb-action/issues/43
