### ISSUE TITLE
Loop docs

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#2066]
We don't have these yet

@snth maybe we could use some of your "gradient descent" 😱 example? Or possibly there are more practical examples we could use?

**Comment by snth** [comment]
I've been thinking about this since yesterday and where I'm at rn is I'm planning to do a series of 3 blog posts:
1. Introductory (but including something special) to be done by Monday.
2. Graph and tree algorithm examples
3. Online Gradient Descent and regression

These will include examples which we can include in the docs. The first piece I want to have done by Monday.

I want to hold back on the OGD examples because I want to see if we can eliminate the need for `_frame` references with a 0.6.1 release. (I edited your post to remove the example so it doesn't get "leaked"/posted somewhere by someone in the unfinished form.)

If you want a basic example for the 0.6.0 release then I can probably have that for you in 13-14 hours time.

**Comment by max-sixty** [comment]
> If you want a basic example for the 0.6.0 release then I can probably have that for you in 13-14 hours time.

No huge rush but if you would be up for adding a short doc, that would be great. This feature I'm less personally excited by than you, I think (just because I've never myself used recursive functions)

**Comment by max-sixty** [comment]
Sorry, actually we do have them! https://github.com/PRQL/prql/blob/6388d7c05dea77908c95e55a42018d699ba75212/book/src/language-features/standard-library/loop.md

(I was looking at the live site, and the GHPages deployment silently broke, now fixed)

**Comment by snth** [comment]
I will try to add some more examples as I write them up.

**Comment by max-sixty** [comment]
> I will try to add some more examples as I write them up.

That would be great! Thanks. Lmk if you need any help with the tests / snapshots etc, should be totally seamless, but if it's not...
