### ISSUE TITLE
Check if table exists, UPSERT, REPLACE

### ISSUE THREAD

**Issue by culebron** [PRQL/prql#21]
**Rationale**

A large part of work with SQL databases is maintenance of statics. E.g. you run a predictive engine (ML or simple regressions) and some variables are current stats, like "amount of orders in the recent 1 hour". These tables are then queried often by predictive services or libraries.

Currently, we chose to do this with normal tables, and have to truncate or recreate them. Other ways of doing this with SQL would be VIEW or MATERIALIZED VIEW. But their main drawback is that they must be in the same DB as the source table, and block maintenance on it: ALTER TABLE becomes impossible (or requires recreation of the views).

That's why many use some Python code to extract data, transform and load in another DB. (An important requirement is to have just one such Python script per feature, that does both inititalization and updates. Because any business will generate many features, and doubling them and scattering the logic creates a lot of extra pain.)

Such operations require several kinds of actions:

1. **UPSERT**
 
Example 1: re-calculate total orders per city/client every day and store in a separate table (for performance reasons).
Example 2: maintain log-like table: select new orders from source table, but only a set of fields, transform, insert into another DB.

Without upsert, you have to run a program to do maintenance and call SQL scripts.

1. check if the target stats table exists
2. create if it doesn't (because we want to do both creation and update in one code unit)
3. check if the stat is recent, or requires update (this can be necessary if we had a large system outage and not sure if our logs are correct)
4. If this is on another DB, you have also to create temporary tables and insert the aggregated data into them
5. after all that run 2 SQL commands:

    insert into city_stat 
    select o.city_id, count(*) orders, sum(o.cost) cost, current_time as update_timestamp
    from orders o left join city_stat c on o.city_id=c.id
    where c.id is null
    group by o.city_id;

    update city_stat
    from orders o inner join city_stat c on o.city_id=c.id
    set orders = count(*), cost=sum(o.cost), update_timestamp=current_time
    where city_id=o.city_id
    group by o.city_id;

Upserts in noSQL databases make this quite trivial:

    upsert db/table
    from <select query>

**Note 1** probably it should support table recreation.

**Note 2: it should also support increments to existing and to non-existing records.** E.g. 

    upsert city_stats
    set orders = (orders or 0) + i where city_id = j
    from (some input data here ....)

2. **REPLACE** table data

Sometimes you need to keep just current stats, e.g. orders within last 1 hour per district/neighborhood.

Pandas package recognized this need and made it possible with a [to_sql](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_sql.html) function:

     city_orders_stat.to_sql(sql_alchemy_connection_obj, 'city_stat', method='replace')

in this case the table will be dropped and recreated.

In SQL, it must be broken down into 4 stages:

1. test if target table exists (again, this should be done, because we want to keep minimum number of scripts per feature)
2. drop or truncate
3. recreate if necessary
4. create as select or select if in another db
5. insert if in another db

**Comment by max-sixty** [comment]
Thanks for the issue @culebron !

I had added some ["non-goals" to the readme](https://github.com/max-sixty/prql#non-goals) — they're certainly not permanent, but we should be really focused on what we can realistically build, and that needs to start with generating analytical queries. DDL is listed as a "non-goal" at the moment.

I'd welcome others adding a :+1: or comment here if this is important for us to have DDL in order to get to a version that people will use. And thanks again for writing the issue.

**Comment by culebron** [comment]
@max-sixty I did check non-goals. Why do you think REPLACE or UPSERT is a DDL operation? It seems to me that it's not data definition at all, they both just push the data somewhere, no matter what type it has.

Both operations will effectively allow getting rid of the procedures that I listed. In any serious application, you spend more time on this (which is working around SQL shortcomings), rather than on SELECT queries.

**Comment by max-sixty** [comment]
Sorry that I'm misusing terms — I had meant outside the focus of "read" queries.

Let me modify the non-goals a bit, because they're currently expressed too confidently relative to how much information I have. You're right those sorts of operations are important in large projects. My perspective is that SQL is particularly bad at read-queries relative to their semantic content, and so we should focus on those to start. But I'm totally open to seeing this grow to whatever people find helpful.

Again re welcoming others adding a 👍 or comment here if this is important for them.
