### ISSUE TITLE
Scope variables within splits

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#213]
We're currently getting `AVG(AVG(salary)) AS avg_salary,` in https://github.com/max-sixty/prql/issues/194:

```sql
WITH table_0 AS (
  SELECT
    AVG(salary) AS emp_salary,
    *
  FROM
    employees
    LEFT JOIN salaries ON salaries.emp_no = employees.emp_no
  GROUP BY
    employees.emp_no
),
table_1 AS (
  SELECT
    AVG(AVG(salary)) AS avg_salary,        # <- whoops
    *
  FROM
    table_0
```

Unfortunately this may require some rethinking of the structure — currently `materialize` materializes all variables & functions, without knowing anything about the splits. But here, because we have a new split / CTE, we _can_ use the previous variable name.

Possibly we can have a rule of retaining the name in `aggregate` clauses — it'll work in the following CTEs, and it'll work in `having` & `order by` clauses (at least in most DBs)...

**Comment by aljazerzen** [comment]
I thinks there is still an issue:

```elm
from dept_manager
aggregate by:emp_no [
  count: count *
]
derive [
  mng_no: dept_manager.emp_no
]
join employees [employees.emp_no = mng_no]
```

produces:

```SQL

WITH table_0 AS (
  SELECT
    COUNT(*) AS count,
    dept_manager.emp_no AS mng_no
  FROM
    dept_manager
  GROUP BY
    emp_no
),
table_1 AS (
  SELECT
    *
  FROM
    table_0
    JOIN employees ON employees.emp_no = dept_manager.emp_no
)
SELECT
  *
FROM
  table_1
```

JOIN employees should use SQL alias `mng_no` instead of materializing into `dept_manager.emp_no`.

I believe that this requires that we know the scope of each alias during materialization and the scope is bound to its atomic pipeline. Which means that splitting the pipeline into atomic pipelines must be done during materialization.

Please tell me that I'm wrong :cry: 

Wait, why are we even materializing the aliases? Could always we just left the mng_no unresolved?

**Comment by max-sixty** [comment]
Thanks a lot for raising this @aljazerzen .

> Wait, why are we even materializing the aliases? Could always we just left the mng_no unresolved?

Yes you're completely right. In this specific case, we should leave it unresolved.

Currently the materialization:
- Converts every variable to its underlying representation
- ...until it hits an `aggregate`, when it stops doing that

It stops because in https://github.com/max-sixty/prql/blob/58f7c66352b06d56a5eed715ad35df07210f088e/tests/test_transpile.rs#L148 we don't want to have `AVG(AVG(...))`. (but in https://github.com/max-sixty/prql/blob/58f7c66352b06d56a5eed715ad35df07210f088e/tests/test_transpile.rs#L56 we _do_ need to convert it, because of the `derive`.)

So it makes a mistake here — instead it should only stop materializing the results of `aggregate` variables.

I _think_ we might be able to do this by not adding the assignments in `aggregate` transformations as variables, and removing the second bullet above.

I'm not confident that this will solve _all_ the problems, but it should solve this one. WDYT @aljazerzen ? Tell me if I'm missing something!

**Comment by aljazerzen** [comment]
I think variables should be cleared between atomic pipelines:

```
from invoice
select price_one: total_price + 1
take 10
derive price_two: price_one + 1
```
... compiles to ...
```
WITH table_0 AS (
  SELECT
    TOP (10) total_price + 1 AS price_one
  FROM invoice
),
table_1 AS (
  SELECT 
    *,
    total_price + 1 + 1 AS price_two
  FROM table_0
)
SELECT * FROM table_1
```
... which produces an error, because in second select, `total_price` is not in scope anymore.

So this means we should not be replacing all variables into their declarations. But sometimes we have to:
```
from invoice
select price_one: total_price + 1
filter price_one > 5
```
```
SELECT total_price + 1 AS price_one
FROM invoice
WHERE total_price + 1 > 5
```
because WHERE does not work with aliases.

- doesn't work with alias: where, having, group by
- works with alias: order by

This means that we either:
1. split into atomic pipelines during materialization
2. pass info about variables to translation

In any case, we have to better define what current scope is, as I said in #222

**Comment by max-sixty** [comment]
OK so the current rules are now:
- Collect variables & values except those in `aggregate`s
- Convert each variable to its value

The proposal is to:
- Collect variables & values except those in `aggregate`s
- Convert each variable to its value
- Clear variables when we start the next atomic pipeline / CTE

...is that what you were thinking too? I think that covers the cases above.

As you suggest, the challenge here is that the materialization — where we clear the variables — currently comes before the translation — when we know about the next atomic pipeline.

The "[worst case alternative approach](https://github.com/max-sixty/prql/issues/247#issuecomment-1075792684)" would work here, but would make the code more coupled.

(Potentially related to https://github.com/max-sixty/prql/issues/247, given inter-CTE variables — _possibly_ we could use the same approach to scope variables to the CTE?)
