### ISSUE TITLE
Integration test for different DBs in CI

### ISSUE THREAD

**Issue by Jelenkee** [PRQL/prql#2211]
### What's up?

Hi,
I noticed that there is an integration test with SQLite, DuckDB and Postgres that does not run in CI. Is there a special reason for that?

I think it would be cool to run tests for different vendors like MySQL (or MariaDB) in CI as well. Even IBM DB2 and MS SQL Server have public docker images that can be used.
The tests should cover the syntactic/semanctic differences between theses vendors (like SUBSTR vs SUBSTRING) so that issues like #1854 can be discovered earlier.

We can adapt the workflow from objection.js which looks pretty simple
[workflow](https://github.com/Vincit/objection.js/blob/master/.github/workflows/test.yml)
[docker-compose](https://github.com/Vincit/objection.js/blob/master/docker-compose.yml)

It may not be necessary to fill the DBs with chinook before testing. Just a few records in a table may be enough.

**Comment by max-sixty** [comment]
Great, thanks for the issue @Jelenkee 

I think that we do run the SQLite & DuckDB tests in CI — they run as part of `cargo test`, because they can run in-process — i.e. no need to run a separate executable.

We could definitely run tests in CI for other DBs with `docker-compose`, and this will become increasingly useful as we develop more dialect-specific features. One nice feature about `docker-compose` is that they're also fairly easy to run locally, and we can add a single command to `task test-all` to have those run as part of that.
