### ISSUE TITLE
Clickhouse support 

### ISSUE THREAD

**Issue by RealHarshThakur** [PRQL/prql#2224]
I'd love to see PRQL directly compiled into Clickhouse SQL.  
ClickhouseSQL has really handy [aggregate functions](https://clickhouse.com/docs/en/sql-reference/aggregate-functions/reference) that would really cool to have PRQL too.

**Comment by max-sixty** [comment]
Hi @RealHarshThakur — we do have a ClickHouse dialect in our dialects — https://prql-lang.org/book/language-features/target.html — though very little is implemented specifically for ClickHouse

We're very open to contributions for ClickHouse-specific features

If there are folks who are keen to contribute, we can use this issue to prioritize the features; otherwise we can close the issue but keep our eyes open for opportunities here.

**Comment by max-sixty** [comment]
Closing but thanks for the issue and please feel free to open an issue prioritizing ClickHouse-specific features, or an initial contribution on them.
