### ISSUE TITLE
Crash on `(take)`

### ISSUE THREAD

**Issue by vanillajonathan** [PRQL/prql#2270]
### What happened?

Application crashes.

### PRQL input

```elm
from tracks
group tracks.* (take)
```

### MVCE confirmation

- [X] Minimal example
- [X] New issue

**Comment by aljazerzen** [comment]
Just a note for people (mainly me when I forget) where this bug is at:

We can fix it now with @max-sixty's PR, but the right why would be to improve our type checking to thrown an error earlier.

It's all already there, we only need a syntax for types of functions, so functions in std can be properly annotated. And this depends on having a syntax for lambda functions.

**Comment by max-sixty** [comment]
OK great, very much agree with the diagnosis.

I'll close this, since #2325 has the test in `bad_error_messages.rs`, and the immediate issue is "Fixed™"
