### ISSUE TITLE
`ErrorMessage` lacks `MessageKind`

### ISSUE THREAD

**Issue by vanillajonathan** [PRQL/prql#2285]
The `ErrorMessage` struct in `prql-compiler/src/error.rs` lacks the `MessageKind` enum.

**Comment by max-sixty** [comment]
Why is this a bug / what's the problem here?

(not claiming that it's not / that there's no problem, asking the question so we know how to proceed). FWIW `@aljazerzen` is out for another ten days and was the author here.

**Comment by vanillajonathan** [comment]
Because I saw there was discussion about having a `MessageKind` enum, and then I saw it was available from the C library, so then I wanted to use it from the Rust crate but was surprised to see it was nowhere to be found.

**Comment by max-sixty** [comment]
Yes totally, we can add this to the `ErrorMessage` struct. Note that everything is an `Error` at the moment, so there's not much we can do usefully with it at the moment, but we added it to `prql-lib` because we wanted to make that API future-proof. 

I'll switch the labels on the issue if that's OK. Contributions welcome here.
