### ISSUE TITLE
Install with brew

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#233]
Could we add PRQL to brew? I'm not sure what that requires...

**Comment by max-sixty** [comment]
I am probably not the best person to do this: 

From https://docs.brew.sh/Acceptable-Formulae:

> We frown on authors submitting their own work unless it is very popular.

...assuming this means popular by usage rather than GH stars :)

**Comment by roG0d** [comment]
Hi!
I'm currently working on this. I'll inform of any progress over here

**Comment by roG0d** [comment]
Do we have an official [homepage](https://docs.brew.sh/Formula-Cookbook#fill-in-the-homepage)?
> We don’t accept formulae without a homeage!

I've seen that the github repo is not considered a valid one in order to get to `homebrew/core`. I assume that is because is needed by the [Formula API](https://rubydoc.brew.sh/Formula#homepage%3D-class_method)

The only similar thing I've found is the [PRQL Language Reference](https://lang.prql.builders/introduction.html). but I'm not sure if they'll approve it.

**Comment by max-sixty** [comment]
We have a provisional one at https://prql.github.io/prql-website/ . Is that sufficient?

(FWIW there's a designer doing a pass of it, which should be ready in a week or two...)

**Comment by roG0d** [comment]
Yeah! I assume that's exactly what they want 😁 I'll include it in the formula of the app.

For now, I've achieved to tap the formula to my local brew directory. I've try it already and it gets installed and running. It's a rough version, but it's works.

Now I would like to check and polish the dependency thing cause for now it's only builded with cargo. [Here you have](https://github.com/roG0d/homebrew-prql/blob/main/Formula/prql.rb) the repo with everything I've done until now.

I'll keep this issue updated with any progress!

**Comment by max-sixty** [comment]
Thanks a lot @roG0d! Greatly appreciated. The repo looks good. Does that get PR-ed into `brew` itself, or remain as a separate repo?

Let us know if you need anything from our end.

**Comment by roG0d** [comment]
Just only in the best sceneario, which is that homebrew approved it. it effectively gets PR-ed intro [homebrew/core](https://github.com/Homebrew/homebrew-core/tree/master/Formula). 

For now on I'm getting helped by @antferdom but if we need something we will let you guys know over here or by discord!

**Comment by max-sixty** [comment]
Great, thanks. And thank you @antferdom, awesome that you're involved.

**Comment by antferdom** [comment]
Thanks @max-sixty!, I was scared of how and where I was supposed to begin contributing, but it wasn't until my good friend Rodri pushed me right into the action.

**Comment by roG0d** [comment]
Hi guys!
I've done some basis [tests](https://github.com/roG0d/homebrew-prql/actions/runs/2235600675/workflow) on GitHub Actions as @max-sixty commented and it's works fine! 

In order to get to `homebrew/core` I assume it has to be tested like that on the 3 latest version os macOS and linux. But I was thinking about if it's even worth to try manage the homebrew repo when we could just simply tap it and treat it just like a normal brew package, it's less professional but we could skip all the [Aceptable Formulae](https://docs.brew.sh/Acceptable-Formulae) process and let people have it right now. Let me know what you think about it! 

All this assumption is based on my worries about prql not being "known enough" by homebrew criteria (which, indeed, is indefined :sweat_smile:) based on the downloads numbers of the [crate](https://crates.io/crates/prql) in Rust. 

I don't know, the uncertain about acceptable formulae is driving me nuts :joy:

**Comment by max-sixty** [comment]
Definitely re adding a tap at first! 

My guess is that users > GH stars for their criteria :). And so we are a bit short at the moment for `core`. But hopefully we'll convert the latter into the former in time.

Would you be up for PRing that code @roG0d ? Is there code that we would run on every release to build and update the version?

**Comment by roG0d** [comment]
Perfect then :D 

About the PR absolutely yes! But this code needs to be in a different repo on the prql organization, something like prql/homebrew-prql. 
And about that version code it would be the next thing I'll be working on, so if you could create me a dev branch or something like that on the new repo it would be awesome!

**Comment by max-sixty** [comment]
Great, I added you to https://github.com/prql/prql-brew. Feel free to experiment there and we can refine things later!

**Comment by roG0d** [comment]
Thanks max! but I forgot to insist on the naming covention 😅
Indeed, I had read it somewhere and I've just found out that was on the official [homebrew page](https://docs.brew.sh/Taps#repository-naming-conventions-and-assumptions) so if you could change the repo to prql/homebrew-prql that would be great!
> On GitHub, your repository must be named homebrew-something to use the one-argument form of brew tap. The prefix “homebrew-“ is not optional.

Sorry for the inconvenience! :P

**Comment by max-sixty** [comment]
No prob, done!

**Comment by roG0d** [comment]
Hi max, I think it's done! I let you the [link](https://github.com/prql/homebrew-prql/issues/1) to the issue where I've been commenting all the solution! There are some things I would like to tell you about, but I think it's pretty much done!

**Comment by ankane** [comment]
Hi, just wanted to let you know that `prql-compiler` is now available in Homebrew Core.

Refs:

- https://github.com/Homebrew/homebrew-core/pull/106489
- https://github.com/Homebrew/homebrew-core/pull/106597

**Comment by max-sixty** [comment]
@ankane — that's awesome — thanks a lot!

Do you know how people generally keep these up to date? We have a workflow that updates `homebrew-prql` in https://github.com/prql/prql/blob/c628d9897d7d35170fd9bd12754fc6630eb061fe/.github/workflows/release.yaml. 

Could we instead just run `brew bump-formula-pr`?

Do you happen to know how we should deprecate the existing version? (No problem if not, not sure how much of a brew expert you are...)

**Comment by ankane** [comment]
I've seen [this action](https://github.com/dawidd6/action-homebrew-bump-formula) recommended by a Homebrew maintainer.

For deprecation, I believe you can add something like this to the existing version:

```ruby
deprecate! date: "2022-07-26", because: "now in Homebrew Core"
```
