### ISSUE TITLE
Tweaks for integration tests

### ISSUE THREAD

**Issue by Jelenkee** [PRQL/prql#2353]
### What's up?

Some follow-ups for #2286 

* [ ] Remove previous integration tests, move the data files into this path
* [ ] Run in-process DBs even without an external connection (will be quite helpful if we start using this more)
* [ ] Add a description & link to https://github.com/prql/prql/blob/7ae804a9d3f42f6ed3d33c04ab910dca164c7efc/web/book/src/contributing/development.md#L310
* [ ] Implement whether to run external integration tests with a feature, rather than reading the CI env var (that could become a bit confusing otherwise)
- [ ] (minor) Possibly output the snapshots as CSVs / something both machine & person-readable, e.g. with headers, rather than one long line
- [ ] (minor) Consider whether we keep it in the current CI test vs move to another, possibly in test-all.yaml. It currently adds 40 seconds, which is not too bad. Or we condition the test-rust tests on a PR's paths, and avoid running it for small doc changes.
- [x] When starting docker compose the owner of prql-compiler/tests/integration/data/chinook is changed on Linux. Probably on macOS too. That should be fixed because you cannot edit the files in there. #2352

(edited by @max-sixty to add an item that @Jelenkee suggested. And now completed)

**Comment by max-sixty** [comment]
>  Implement whether to run external integration tests with a feature, rather than reading the CI env var

Specifically for this, I was thinking:
- We have a [feature](https://doc.rust-lang.org/cargo/reference/features.html) in `prql-complier` called something like `test-external-dbs`, which is not `default`
- We put the list of tests to run under the feature (or use `cfg-if` if needed), so it's the longer list when that feature is active
- Run in CI with `--all-features`
- Remove the special-case code around CI from the library
- (minor) Also put dependencies behind this feature, so we didn't need to compile them otherwise

This would mean we get dependable, hermetic external tests, _and_ still get the in-process tests by default
