### ISSUE TITLE
Website with mdbook

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#256]
The `mdbook` is really good! I think it's perfect for the language reference.

As suggested by @aljazerzen , it would be great to get this onto GitHub Pages (or something similar). I can have a look at doing this at the weekend unless anyone is more familiar with it.

I'm also going to do some work to improve the content, which I haven't touched in too long! And some small things like links don't work any longer, which I can fix.

**Comment by aljazerzen** [comment]
Yeah links need to be fixed. 

Mdbook is real simple, because you just write markdown and add sidebar into `SUMMARY.md`. So the main thing here is the content. We have to document the language, how read function calls, that `by` in `aggregate by` is a named parameter. Essentially this: https://www.postgresql.org/docs/14/sql.html

(I'm always leaning on postgres for references and how they do things. It's just the database I know best)

**Comment by max-sixty** [comment]
Closed by https://github.com/max-sixty/prql/pull/282
