### ISSUE TITLE
What is the difference between prql and esProc SPL?

### ISSUE THREAD

**Issue by songlinshu** [PRQL/prql#2580]
### What's up?

https://github.com/SPLWare/esProc

**Comment by max-sixty** [comment]
I don't have a complete answer — open to thoughts! 

One major difference looks like PRQL focus on pipelines; I don't see the same emphasis in esProc? It looks more based around a spreadsheet-like syntax.

In terms of the runtime — esProc requires a Java VM.

I'll close since it's not really a PRQL issue, but feel free to add thoughts / things we could learn from each other.
