### ISSUE TITLE
Join tuple equivalence

### ISSUE THREAD

**Issue by aljazerzen** [PRQL/prql#2641]
### What's up?

Currently, the second arg of join takes either:
```
# - scalars
join rel cond1

# - tuples
join rel {cond1, cond2, cond3}
```

In #469 we changed `filter` not to accept tuples and force the user to either use `&&` or multiple filters.

The reasoning for this change is based on a move away from implicit `&&` that are inserted into the tuple to convert it into a boolean expression. One may incorrectly assume the tuple means "any of the conditions" and not "all of the conditions".

@snth left [a comment about this here](https://github.com/PRQL/prql/issues/2124#issuecomment-1563462793).

**Comment by aljazerzen** [comment]
Examples of the proposed change:
```diff
   from a
-  join b {==a_id}
+  join b (==a_id)
```

```diff
   from a
-  join b {a.name == b.name, a.number = b.number}
+  join b (a.name == b.name && a.number = b.number)
```

PS: in the first example, parenthesis are required because without them, the join would be parsed as `join (b == a_id)`

**Comment by max-sixty** [comment]
I'm +0.5

**Comment by aljazerzen** [comment]
Oh, and @max-sixty [left a comment here](https://github.com/PRQL/prql/pull/2612#issuecomment-1563857616).

I forgot to mention that I'm +1 on this, which is a majority.

It turns out that it issue is just documenting something we already agreed on :D

**Comment by max-sixty** [comment]
I would add — it would be great to make a good error message! Even for those not using `join` already, I'm sure they'll make the mistake given how prevalent the singleton / tuple equivalence is...

**Comment by snth** [comment]
I'm +1 on replacing `{}` with `()` for join conditions for the reasons mentioned.

One clarification please: does this mean the `()` is essentially mandatory for any `join` that has a join condition, i.e. anything other than a `CROSS JOIN`? I think that would be a good thing because it gives a visual consistency.

---
I'm -1 on the idea I floated in https://github.com/PRQL/prql/issues/2124#issuecomment-1563462793 of delineating the join conditions with a keyword like `on` or `where`.  I don't like how those examples looked and the examples with `()` are more visually consistent with the rest of the language.

**Comment by aljazerzen** [comment]
> One clarification please: does this mean ...

Yes, `()` would be mandatory, because you'd be using binary or unary operators, which all require `()` when used as arguments to functions. It would not be required for cross join, as one can use just `true`:

```
from a
join b true
```

----

To be honest, I didn't quite understand what you meant in the PR comment, about `on` or `where`. Now that I do, I also don't like adding keywords specifically for the join function.
