### ISSUE TITLE
Multiple consecutive `sort` clauses

### ISSUE THREAD

**Issue by YuxiLing** [PRQL/prql#2683]
### What's up?

prql version: 0.8.1

comments: The usage of multiple consecutive `sort` clauses seems to be disallowed, and should be written in one line/operation.

May I understand this way? The last `sort` operation would overwrite all the ordering features from the previous steps. In other words, the effect of `sort` clause is overwritten instead of cumulated.

I'm not sure if a warning from the compiler might be better or if highlight it in the documentation would be helpful.

prql code:
```
from tb1
sort c1
sort [c2,-c3]
```
sql code:
```
SELECT
  *
FROM
  tb1
ORDER BY
  c2,
  c3 DESC
```

Thanks.

**Comment by aljazerzen** [comment]
This is intended behavior. Consecutive sorts override one another.

I do agree that compiler should emit a warning saying "this sort is useless, consider removing it".

**Comment by max-sixty** [comment]
Agree a lint would be nice

I would probably vote to have this as a lint on a static query, rather than a warning at runtime. If a tool is building the query dynamically, it's completely fine to have consecutive `sort`s — indeed that's some of the elegance of the pipeline approach.

We don't yet have an ability to add lints, so I'd suggest marking this as Postponed. But fine to leave reopen if others prefer?
