### ISSUE TITLE
Type aliasing

### ISSUE THREAD

**Issue by vanillajonathan** [PRQL/prql#2920]
### What's up?

PRQL could have support for type aliasing.

For example someone might want to create a type alias called `CustomerNumber` that is a type alias to `int16`, or a type alias called `Celsius` that is a `float`, or a alias called `Point` that is a `(int8, int8)` tuple.

**Comment by aljazerzen** [comment]
PRQL will have this in 0.9, it is described in https://github.com/PRQL/prql/blob/main/web/book/src/compiler/internals/type-system.md and mostly implemented.

Your examples would be defined as such:

```elm
type CustomerNumber = int

type Celsius = float

type Point = {int, int}  # tuples use {} in PRQL
```

You could then use the type as function param type:

```elm
let my_func = c_num <CustomerNumber> -> ...
```

Or table definition (not yet implemented, see #2646):

```elm
let my_customers <[{
   num = CustomerNumber,
   name = str || null,
}]>
```

**Comment by aljazerzen** [comment]
But there is something important we need to decide on: is `CustomerNumber` a new distinct type, or just an alias to `int16`? This distinction affect this code snippet:

```elm
type CustomerNumber = int

let my_func = c_num <CustomerNumber> -> ...

let res = my_func 4
```

If `CustomerNumber` is a new type, this would fail with "my_func expected CustomerNumber, but found `int`".

---

I prefer that `CustomerNumber` is just an alias, since that is much more convenient and we'd have to invent new syntax for constructing `CustomerNumber` otherwise.

**Comment by vanillajonathan** [comment]
Maybe there could two keywords, one for defining a type alias, and one for defining a new type. Haskell uses the keyword `newtype` to create a new distinct type.

**Comment by aljazerzen** [comment]
Oh, interesting: a language that does both!

I've just realized that Rust has a similar thing:

```
struct CustomerNumber(int64);
```

It's not a keyword, but a tuple struct with only one element. Because there is only one element, it's size and representation is identical to `int64`, but it acts as a new type.

Ok, this means that the type alias can be just an alias and not a new type. For constructing a new type, we can use tuples with a single element or even add a keyword, as in Haskell.

Ref #1965 

I'm closing this issue, if there is anything else, feel free to re-open.

**Comment by vanillajonathan** [comment]
You would expect to be able compare two instances of tuple structs, so in Rust you have to derive from the `PartialEq` macro, also you would want to be able to print it so you would want some kind of "to string" function.

**Comment by aljazerzen** [comment]
Yes, that is the point of a new type: restrict the access to all of the functions / operations that operate with the original type.

Are you saying that PRQL should have something similar to Rust's derive macro?

**Comment by vanillajonathan** [comment]
No, I am saying that when creating a new type it should provide the functionality that the `PartialEq` macro in Rust does. If PRQL were to support newtype support, it should include equality testing and functionality to stringify. If you create a new Celcius type, you should be able to use `+` to like `let celcius = celcius1 + celcius2`.

**Comment by aljazerzen** [comment]
Ok, I see, we are saying the same thing.

And I agree, for newtypes we'd need some kind of derivation of operator implementations.
