### ISSUE TITLE
Questions about `pl::ExprKind`

### ISSUE THREAD

**Issue by not-my-profile** [PRQL/prql#2983]
* What's the difference between a `Tuple` and an `Array`? Both variants contain `Vec<Expr>`. The book doesn't mention either tuples or arrays ... just [lists](https://prql-lang.org/book/syntax/lists.html).

* What's an `RqOperator`? Is it always a function from the [standard library](https://prql-lang.org/book/language-features/standard-library/)? How is the `Internal` variant related to this?

**Comment by aljazerzen** [comment]
Recently, we've formalized this distinction between tuple and array and changed syntax a bit.   That's why the docs don't reflect the change yet.

  In short, tuple can contain different types in each field, but must have fixed number of fields (known at compile time). Array must have all items of the same type, but can have varying number of items. You can read more about that here: https://github.com/PRQL/prql/blob/main/web/book/src/compiler/internals/type-system.md#container-types

----

`RqOperator` is a PL expr kind, that is later compiled to [`rq::ExprKind::Operator`](https://github.com/PRQL/prql/blob/main/prql-compiler/src/ast/rq/expr.rs#L30-L33). All functions, binary operators, unary operators and f-strings are compiled to `RqOperator`s, with intention of limiting the complexity of the RQ. They are then implemented for SQL in [std.sql.prql](https://github.com/PRQL/prql/blob/main/prql-compiler/src/sql/std.sql.prql).

Internal is trick to trigger some special compiler behavior - some kind of a keyword that allows the compiler to treat some functions differently. The rule is that [if the internal id starts with "std."](https://github.com/prql/prql/blob/main/prql-compiler/src/semantic/resolver.rs#L595-L604), it will compile directly to `RqOperator`. Otherwise there are custom compiler implmentations in transforms.rs. This is obviously not part of the public interface.

**Comment by richb-hanover** [comment]
Hello @not-my-profile - It's good to see your thoughts about PRQL. @aljazerzen wrote:

> Recently, we've formalized this distinction between tuple and array and changed syntax a bit. That's why the docs don't reflect the change yet.

This reminds me - do we need a new page in the Book (perhaps near 4.2 Tuples) that describes Arrays? Perhaps that page becomes "Tuples and Arrays"...

**Comment by max-sixty** [comment]
Is this question answered? I'll close but we can reopen if not.

(@not-my-profile hope all is well!)
