### ISSUE TITLE
Stop leaking chumsky error types from prql_parser

### ISSUE THREAD

**Issue by aljazerzen** [PRQL/prql#3108]
Follow up for https://github.com/PRQL/prql/pull/3000#discussion_r1272323992

Currently, `prql_parser` crate emits a special error type:

https://github.com/prql/prql/blob/e0fd9202d61390a452cef331fbe685a7d02e9562/crates/prql-parser/src/lib.rs#L20-L24

In the `prql_compiler::parser` we then map the error into the `prql_compiler::Error`.

I propose we emit `prql_compiler::Error` from `prql_parser` instead. This will:
- make chumsky an internal detail of the parser,
- standardize a single error type over all of the compiler crates,
- require `prql_compiler::Error` to be moved to a new `prql_common` crate or maybe `prql_ast`?
- make lexer an internal detail of the parser,

@not-my-profile

**Comment by not-my-profile** [comment]
If we want to make chumsky an implementation detail we should create thin wrappers around its error types within the parser crate ... however we certainly shouldn't emit `prql_compiler::Error` from `prql_parser` ... a parser cannot emit compiler errors ... it doesn't do compilation.

**Comment by aljazerzen** [comment]
Well then it would be `prql_common::Error` :D

You don't seem to treat the parser as a part of the compiler? It is producing the AST specific to this compiler.

**Comment by aljazerzen** [comment]
Alternatively, we could create a new `prql_parser::Error` that is a copy-paste of the `prql_compiler::Error`.

**Comment by not-my-profile** [comment]
> It is producing the AST specific to this compiler.

`prql_ast` should contain nothing compiler specific. Yes I know it currently contains `ExprKind::Internal` but I'll remove that.

And no `prql_compiler::Error` is a really poor error type since it just stringly types errors ... we certainly don't want to duplicate it anywhere.

**Comment by aljazerzen** [comment]
Actually, thinking about it, maybe we should simplify the `prql_compiler::Error` and embrace what it is:

```rust
struct Error {
  message: String,
  span: Option<Span>,
  code: Option<String>,
}
```

**Comment by aljazerzen** [comment]
I still find the idea that parser is not the part of compiler strange. I'd say that "parsing" is part of "compiling". Technically, it may be not, but in the same way as PRQL codegen or SQL codegen is not. And after that you are left with just a few IR mappings?

Other projects consider [the parser](https://doc.rust-lang.org/beta/nightly-rustc/rustc_parse/index.html) and [AST](https://doc.rust-lang.org/beta/nightly-rustc/rustc_ast/ast/index.html) [parts](https://github.com/openjdk/jdk/blob/master/src/jdk.compiler/share/classes/com/sun/source/tree/IfTree.java) of their compiler efforts.

**Comment by not-my-profile** [comment]
>  maybe we should simplify the prql_compiler::Error and embrace [stringly typed errors]

No ... we should get rid of stringly typed errors ... even if the only thing we care about are good error messages: strongly typed errors lead to better error messages, since they will then clearly and consistently indiciate in which part of the compilation process the error originated.

Indeed I think that it would make sense to move PRQL codegen out of the compiler crate. And I'd rather call it PRQL formatting than codegen. Ad SQL codegen not being part of it ... that depends on what we consider the compilation target. If we say that it's a PRQL to SQL compiler then the SQL codegen is part of it.

**Comment by aljazerzen** [comment]
> we should get rid of stringly typed errors

Yeah, true. Eventually.

> it would make sense to move PRQL codegen out of the compiler crate

Yup. Also separate frontend (semantic module) and the SQL backend into two crates.

> And I'd rather call it PRQL formatting than codegen

Formatting is just what it is used for - that may make it confusing if we create an SQL-to-PRQL compiler. codegen is also a name for converting an AST into some serialized form in the compiler world https://doc.rust-lang.org/beta/nightly-rustc/rustc_codegen_ssa/index.html.

> If we say that it's a PRQL to SQL compiler then the SQL codegen is part of it.

Well, it a compiler from PRQL source to SQL source.

**Comment by max-sixty** [comment]
> I still find the idea that parser is not the part of compiler strange. I'd say that "parsing" is part of "compiling". Technically, it may be not, but in the same way as PRQL codegen or SQL codegen is not. And after that you are left with just a few IR mappings?

I see it as:
- The parser is the first stage of the compiler (for some definition, obv there are other definitions where it isn't)
- As the project grows in complexity, we modularize it more. We reduce local complexity in exchange for the cost of stricter boundaries.
- Crates are one way of modularizing the project

I say "in exchange for" because stricter boundaries aren't free — we need to add conversions between representations, etc. So we shouldn't do it too early; if we feel like we're doing lots of internal work without adding much functionality, maybe we're modularizing too early...

**Comment by max-sixty** [comment]
> Indeed I think that it would make sense to move PRQL codegen out of the compiler crate. And I'd rather call it PRQL formatting than codegen.

I don't have a strong view on the specific question. I will say — to the extent there's some hesitation to do more crate modularization, I would vote to live with the current approach for a few weeks. For decisions that are less analytical, living with the consequences is often a better way to build consensus. And it's very easy to go faster & slower based on whether we find benefits, relative to going forward & back.

(very much agreed with the rest of this comment)

**Comment by aljazerzen** [comment]
Ok, I'll unify the API a bit, without adding new crates or reducing `Errors` to `message: String`. We can expand that to properly typed errors later.
