### ISSUE TITLE
row-oriented or column-oriented?

### ISSUE THREAD

**Issue by eitsupi** [PRQL/prql#3808]
From https://github.com/PRQL/prql/issues/3782#issuecomment-1806722555

Currently, the relation literal representation in PRQL is row-oriented.

```elm
[
  {a=5, b=false},
  {a=6, b=true},
]
```

However, I believe that the RDBMS for OLAP use and Apache Arrow that PRQL is targeting are often column-oriented.

```elm
{
  a = [5, 6],
  b = [false, true],
}
```

Should they be interchangeable in the PRQL?
Should the latter be a representation of a relation literal to be more appropriate?

**Comment by aljazerzen** [comment]
Current design is row oriented, with following reasons:

1. Many operations are often performed row-wise (selecting, join conditions, filtering).
2. It is not possible to express the column-oriented relation with our type system. That's because one could write this:
   ```
   {
     a = [5, 6],
     b = [false]
   }
   ```
   ... and it would have the same type as the example above. In other words, the type system cannot enforce that the arrays in the tuple will be of the same length. 

---

I also think that:
- they should not be inter-changable, as they have different types,
- maybe we should provide functions that convert from one into the other,
- the representation in PRQL does not dictate how relations are represented at the execution platform - compiler can take row-wise operations and produce columnar operations

**Comment by eitsupi** [comment]
Thanks for the explanation!
Arrays of different lengths are certainly tricky. (I remember previously struggling to get table data passed in such json format and back to the table)

**Comment by aljazerzen** [comment]
Maybe we should add this reasoning into the reference docs? Under the type system as a justification of current design?

**Comment by eitsupi** [comment]
> Maybe we should add this reasoning into the reference docs? Under the type system as a justification of current design?

I think that would be nice!

**Comment by snth** [comment]
> Should they be interchangeable in the PRQL?

I initially thought so but Aljaz makes a great point:

> Many operations are often performed row-wise (selecting, join conditions, filtering).

That's a great point! The logical (mental) model is usually expressed as a list/stream of tuples and I think it makes sense to retain that.

> the representation in PRQL does not dictate how relations are represented at the execution platform - compiler can take row-wise operations and produce columnar operations

Totally agree with this. That's why I thought they should originally be interchangeable.

> Maybe we should add this reasoning into the reference docs? Under the type system as a justification of current design?

Yes, great idea!

Another reason to add is that the number of records/rows/tuples changes a lot more than the column schema. So while there can be some schema evolution, changing the records is the primary use case of data processing system. With this model, PRQL can in theory also operate on unbounded/infinite streams which would be difficult to express in a column oriented design.
