### ISSUE TITLE
Parentheses omitted from sql output in non-commutative operations

### ISSUE THREAD

**Issue by syko** [PRQL/prql#3963]
### What happened?

Attempting to do math fails at BEMDAS in even some pretty basic cases. The compiler seems to omit some parentheses from the output in scenarioes where they are needed.

This seems to be somewhat dialect-dependent. `sql.generic` seems to be perform the worst.

### PRQL input

```elm
from foo
derive {
  a = 10 - (10 - 2),
  b = 10 - (10 + 2),
  c = 10 / (10 / 2),
  d = 10 / (10 * 2),
}
```

### SQL output

```SQL
-- sql.generic
SELECT
  *,
  10 - 10 - 2 AS a,
  10 - 10 + 2 AS b,
  10 / 10 / 2 AS c,
  10 / 10 * 2 AS d
FROM
  foo


-- sql.postgres
SELECT
  *,
  10 - 10 - 2 AS a,
  10 - 10 + 2 AS b,
  (10 * 1.0 / (10 * 1.0 / 2)) AS c,
  (10 * 1.0 / 10 * 2) AS d
FROM
  foo
```

### Expected SQL output

```SQL
SELECT
  *,
  10 - (10 - 2) AS a,
  10 - (10 + 2) AS b,
  10 / (10 / 2) AS c,
  10 / (10 * 2) AS d
FROM
  foo
```

### MVCE confirmation

- [X] Minimal example
- [X] New issue

**Comment by richb-hanover** [comment]
Good bug report. Thanks.

This is a bug in the deployed Playground, it's [fixed in main](https://github.com/PRQL/prql/pull/3846) and [could be rolled into a new release](https://github.com/PRQL/prql/issues/3929) fairly soon

NB I use the [Dev Container](https://prql-lang.org/book/project/contributing/development.html#option-3-use-a-dev-container) to stay up to date with the latest, and to test this...

**Comment by PrettyWood** [comment]
@richb-hanover The bug is still here on `main` (see #3968)
(`a` and `b` were indeed good thanks to #3846 but not `c` and `d`)

**Comment by richb-hanover** [comment]
Yikes! You're right. The addition/subtraction paren's are correct, multiply/divide are not... (See generated SQL below)

@syko Sorry for the misinformation...

```
SELECT
  *,
  10 - (10 - 2) AS a,
  10 - (10 + 2) AS b,
  10 / 10 / 2 AS c,
  10 / 10 * 2 AS d
FROM
  foo

-- Generated by PRQL compiler version:0.10.2 (https://prql-lang.org)
```

**Comment by max-sixty** [comment]
Eeek, I'm looking. Sorry for this...

**Comment by max-sixty** [comment]
OK, so the root of the issue is that for division, we're using s-strings https://github.com/PRQL/prql/blob/192be604162f1afad2f45a4802ca4b0f0094bca5/prqlc/prql-compiler/src/sql/std.sql.prql#L271-L272, which don't have any associativity. For Minus, the compiler implements a fairly robust approach in rust https://github.com/PRQL/prql/blob/cc8addea42abce4ab10b552a6e2de51618239496/prqlc/prql-compiler/src/sql/gen_expr.rs#L802-L846

---

I think we can patch this by putting parentheses everywhere — #3969 — but I think we might need to rethink whether we can use s-strings as extensively as we have been for these operators. We could add an annotation for associativity.

**Comment by richb-hanover** [comment]
@max-sixty I tested this in my Dev Container and it works as expected. Thanks.

> ... but I think we might need to rethink whether we can use s-strings as extensively as we have been for these operators.

Would you give an example or two of where an s-string could run into difficulty?

**Comment by max-sixty** [comment]
> Would you give an example or two of where an s-string could run into difficulty?

I adjusted the approach in https://github.com/PRQL/prql/pull/3970, so it's much more reasonable now — check that one out...

**Comment by syko** [comment]
Nice! That's some fast-action bugfixing 👏
