### ISSUE TITLE
Filter by unselected columns

### ISSUE THREAD

**Issue by eballci** [PRQL/prql#4]
Is it possible to write a query that filters rows by unselected columns. I think if every line is transformation of previous line it is not posibble

**Comment by max-sixty** [comment]
It wouldn't be valid to filter by a column that's been "deselected", because of the pipelined approach, as you suggest.

But if there's no `select` then all columns exist; i.e. this is fine:

```elm
from employees
filter country = "USA" 
```

Does that make sense?

**Comment by rchowell** [comment]
This depends on how far you are willing to push down projections. Max is implying that projections will not be pushed through operators. That is, the schema for one operator depends solely on the previous operator's schema. This is not the case in SQL, but there is a choice to be made here. I think Max's intuition to not push projections through simplifies reasoning about queries, but requires redundant syntax not needed in SQL. 

Consider you wish to create a report with the first and last names of employees from the USA. The report should not include the country because it's redundant.

For example
```
# A. Must select the column to filter?
# What's the syntax for removing `country`?
from employees
select [
  first_name,
  last_name,
  country
]
filter country = "USA"
select [
  first_name,
  last_name
]

# B. Makes the most sense because Scan |> Filter |> Project
from employees
filter country = "USA"
select [
  first_name,
  last_name
]

# SQL projection pushdown will scan `country` 
SELECT first_name, last_name FROM employees WHERE country = 'USA'
```

Example B is actually really interesting. Having the final projection makes understanding the output of a query fairly simple, just like SQL select. Converging on just inverting the logical plan .

**Comment by max-sixty** [comment]
Absolutely @RCHowell — your (B) is how I'm thinking about it:

```elm
from employees
filter country = "USA"
select [
  first_name,
  last_name
]
```

**Comment by eballci** [comment]
I see. There is no strict rules about order of the clauses.
