### ISSUE TITLE
Zig tests started failing

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#4050]
### What's up?

Any idea what caused this? I'm guessing it's an external change, maybe a zig version? I don't think anything has changed in that path, and the commit it failed on is 

https://github.com/PRQL/prql/actions/runs/7412719385/job/20172886376

CC @vanillajonathan as our resident zig expert! :)

Disabled in #4051

**Comment by vanillajonathan** [comment]
Our CI uses the master branch of the Zig compiler. Commit https://github.com/ziglang/zig/commit/c20ad51c621ba18d2c90cc96d1b550831dc5d7a3 changes a bunch of stuff which breaks it because it removes the `linkSystemLibraryName` function.

We use the [goto-bus-stop/setup-zig](https://github.com/goto-bus-stop/setup-zig) GitHub Action which allows us to optionally specify the version of the Zig compiler to use. We could set it to version `0.11.0` for now.

**Comment by max-sixty** [comment]
Yes, either pinning or adjusting for the newer zig sounds good!

**Comment by max-sixty** [comment]
#4053
