### ISSUE TITLE
The various exit status codes from `prqlc`

### ISSUE THREAD

**Issue by richb-hanover** [PRQL/prql#4052]
### What's up?

The `prqlc` compiler returns at least four seemingly different forms of exit status. (Are there more?)

This seems to cause the Playground to give different indications, which are confusing for newcomers. Furthermore, in the error conditions, the SQL pane continues to show previously-generated SQL statements, which may be unrelated to the current PRQL query. 

* Could it be valuable to make the return status a "similar shape"?
* Could the SQL pane update in a reasonable way to show that it's no longer current? (Or is there value to preserving the prior compiled SQL code in that pane?)

Here are test cases I produced in the Dev Container, using recent `main` and 0.11.2. Thanks.

**1. No Errors - this works as expected in the Playground**

```
vscode ➜ /workspaces/prql (main) $ echo "from foo" |   cargo run -p prqlc -- compile 
    Finished dev [unoptimized + debuginfo] target(s) in 0.16s
     Running `target/debug/prqlc compile`
SELECT
  *
FROM
  foo

-- Generated by PRQL compiler version:0.11.2 (https://prql-lang.org)
```

**2. Input contains only a comment - the Playground only displays a squiggly red line**

```
vscode ➜ /workspaces/prql (main) $ echo "# comment" |   cargo run -p prqlc -- compile 
    Finished dev [unoptimized + debuginfo] target(s) in 0.18s
     Running `target/debug/prqlc compile`
[E0001] Error: Missing main pipeline
↳ Hint: Expected a declaration at main
```

**3. Simple error - Playground displays red error pane with helpful message with red squiggly under offending name**

```
vscode ➜ /workspaces/prql (main) $ cat <<'EOF' |  cargo run -p prqlc -- compile 
from inv=invoices
select foo
select bar
EOF
    Finished dev [unoptimized + debuginfo] target(s) in 0.14s
     Running `target/debug/prqlc compile`
Error:
   ╭─[:3:8]
   │
 3 │ select bar
   │        ─┬─
   │         ╰─── Unknown name `bar`
───╯
```

**4. Panic - Playground displays "A compiler bug was encountered"**

```
vscode ➜ /workspaces/prql (main) $ cat <<'EOF' |  cargo run -p prqlc -- compile 
from inv=invoices
join item=invoice_items (==invoice_id)

group { inv.billing_city } (

  group { item.name } (
    aggregate {
      ct1 = count inv.name,
    }
  )
)
EOF
    Finished dev [unoptimized + debuginfo] target(s) in 0.15s
     Running `target/debug/prqlc compile`
The application panicked (crashed).
Message:  cannot find cid by id=128
Location: prqlc/prql-compiler/src/semantic/lowering.rs:949

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

**Comment by max-sixty** [comment]
The main thing I think we could improve is the display of errors in the playground that don't have spans.

For example, in "Input contains only a comment", we could still show the red box that we normally show with the error message at the bottom. That could be a nice PR on the playground

---

I'm open to other ways in the UI of showing the query isn't current, but we do want to retain a view of the most recently valid query, otherwise typing a query is going to be like being in an arcade game, as the query flashes between being valid and invalid.

---

Panics could also be formatted like this, but also we should just try and never panic (current discussion at https://github.com/PRQL/prql/pull/4037#issuecomment-1874426214)

---

(There's a question of whether an empty query should be an error, I'm not sure, plausibly it should be OK but no strong view)

---

I don't see anything wrong about the prqlc CLI exit codes, is there? All the errors return an exit code of 1.

**Comment by richb-hanover** [comment]
These are all good points. I don't have any specific recommendations, I simply wanted to document all that I found when horsing around. I'll close this for now.
