### ISSUE TITLE
Python compiler needs a flag to return the full sequence of errors as json

### ISSUE THREAD

**Issue by brunorpinho** [PRQL/prql#4061]
Hello,

First of all, I would like to thank the devs for the amazing work! You have solved a huge huge huge problem across multiple industries by making this pipeline tool.

I have an use case where I want the full detailed json exception instead of a simple formatted SyntaxError. Is it possible to add a simple flag to the [`compile`](https://github.com/PRQL/prql/blob/aec243c0fe152062ccca8bb819e4ad3c717778ab/prqlc/bindings/python/src/lib.rs#L8) function called `on_exception_return_json` or something like that to get the result of [`e.to_json()`](https://github.com/PRQL/prql/blob/main/prqlc/prql-compiler/src/error_message.rs#L155) into a Python dict? It can even come as a variable of the Python `Exception` class.

I basically need the vector of `ErrorMessage` as json.

Cheers,
Bruno

**Comment by max-sixty** [comment]
Yes, I could see a couple of approaches:

### Another function — `prql_to_sql`

`prql_to_sql` function that is similar to `compile`, but raises an error as pure JSON. It would operate similarly to `prql_to_pl`, which gives a long string of JSON:

```python
prql.prql_to_pl("^")


---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[12], line 1
----> 1 prql.prql_to_pl("^")

ValueError: {"inner":[{"kind":"Error","code":null,"reason":"unexpected ^","hints":[],"span":"1:0-1","display":"Error: \n   ╭─[:1:1]\n   │\n 1 │ ^\n   │ ┬  \n   │ ╰── unexpected ^
\n───╯\n","location":{"start":[0,0],"end":[0,1]}}]}
```

...rather than a nice Error message:

```python

prql.compile("frm artists")


Traceback (most recent call last):

  File /opt/homebrew/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3508 in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  Cell In[3], line 1
    prql.compile("frm artists")

  File <string>
SyntaxError: Error:
   ╭─[:1:1]
   │
 1 │ frm artists
   │ ─┬─
   │  ╰─── Unknown name
───╯
```

I think this could be a quite small PR.

### Add the JSON onto the `Exception`

Browsing the [PyO3 docs](https://pyo3.rs/v0.20.2/function/error_handling), I think we could return an exception which has a `.json` attribute which contains the JSON.

This would be the nicer approach but is a bit more work / requires a bit of work with PyO3...

Edit: I guess the even better thing would be a custom error type which contained the fields — rather than JSON — and then has a string representation with the full error message. But that's a bit more work yet.

---

Any thoughts from others?

**Comment by max-sixty** [comment]
The basic version of this is implemented in #4066; @brunorpinho let me know if that works for you.

I'll close, but we can come back when the next version of PyO3 is out and see if we can do this more elegantly.

**Comment by brunorpinho** [comment]
@max-sixty it absolutely works, all I would need for my use case is that json. Thank you! 

Which version of prql am I expected to see this implemented?

**Comment by max-sixty** [comment]
> Which version of prql am I expected to see this implemented?

It would be in the next release, which we could do quite soon if it'd be helpful. You can also use the version on `main` with ` pip install git+https://github.com/PRQL/prql#subdirectory=prqlc/bindings/python`

**Comment by max-sixty** [comment]
@brunorpinho instead of doing that, use something like this:

```python
try:
  x = prql_to_pl(query)
  x = pl_to_rq(x)
  x = rq_to_sql(x)
except Exception as e:
  json_exception = e
```

...and then in the future, we'll change `compile` to have the information on the object itself.

(I'm planning to revert `prql_to_sql` as it doesn't add much that's useful beyond the snippet above...)
