### ISSUE TITLE
Functions - syntax, scope and limitations

### ISSUE THREAD

**Issue by snth** [PRQL/prql#444]
In issue #437 we ended up with quite a lot of discussion around the syntax for functions. For anyone browsing the issue log that might be quite difficult to find so I'm opening a separate issue for it here. The syntax also gets updated in PR #442 .

The current syntax is described in: https://github.com/prql/prql/blob/main/reference/src/functions.md

@aljazerzen also gave some descriptions on Discord which I've reproduced below:

Currently they are limited to "any expression", but there are plans for them to allow:
- "late binding variables"
```elm
func net gross = gross * (1 - tax)

from finances
select [net gross_salaries, net gross_materials, net gross_something]
```

where tax is column from the finances, but is not resolved until after the function is materialised
- currying
```elm
func add a b = a + b
func add_one = add 1

from employees
select [ age_next_year: add_one age ]
```

- transform functions 
```elm
func take_first col = (sort col | take 1)

from employees
take_first age
```

**Comment by snth** [comment]
The function syntax seems like the least polished aspect of PRQL to me so far. While it has a lot of really elegant ideas from functional languages, my worry is that it's a bit too esoteric for beginners and might confuse them. In my experience, SQL is often something non-programmers pick up coming from Excel and it would be great if we could appeal to those people as well. So while we want to enable concise and logical expression of data pipelines for experienced users, we should also aim to make PRQL easy to pickup for beginners.

I have a number of ideas/comments which are likely to be controversial so I'll break them up into separate comments in oder to make it easier to indicate what you disagree or agree with.

**Comment by snth** [comment]
I like the maxim from the Zen of Python that "There should be one– and preferably only one –obvious way to do it.".

With currying and pipelining I fear that there may be multiple ways of expressing the same thing which may be confusing to beginners. I think the currying in particular is not very beginner friendly.

Also since we're going with the whole pipeline approach, shouldn't we see if we can double down on that and force that for all function applications?

So instead of 
```elm
group [title, country_code] (
  aggregate [
    average salary,
  ]
)
```
have
```elm
group [title, country_code] (
  aggregate [
    salary | average,
  ]
)
```
?

**Comment by snth** [comment]
I'm not a big fan of the `|` symbol for pipelines. While I know it's standard in the unix shell and Jinja templates for example, it's also often used for logical OR and unions in type definitions. Also in regexes `|` is a separator between alternatives so that's what my mind often jumps to.

Moreover there is no intrinsic indicator to a newcomer in which direction the flow of data is. I think something like `>>` would make that more obvious, e.g.

```elm
group [title, country_code] (
  aggregate [
    salary >> average,
  ]
)
```

**Comment by snth** [comment]
- transform functions

```elm
func take_first col = (sort col | take 1)

from employees
take_first age
```

I think this is a bad idea. What happens when I put this in a `derive` block?
```elm
func take_first col = (sort col | take 1)

from employees
derive [
  min_age = take_first age,
  seniority = age - min_age,
]
```
Will that work? I guess maybe it unrolls it into CTE or a subquery? At this stage I don't understand enough about the compiler and how it works. However I see PRQL mostly as a more convenient way to write SQL so I would prefer to keep it at the level where I can predict the SQL that will come out of it.

I would also prefer it if the top level commands in the left column of data pipelines remain keywords so that one can quickly scan a pipeline to see what transformations take place. `take_first` in this example breaks that.

Therefore I propose that functions remain expressions that can be used anywhere within an expression.

If there really is a need for naming common pipeline steps then maybe introduce another language construct for that such as macros or subpipelines or something like that.

**Comment by snth** [comment]
Coming to the function syntax and examples from #437 

```elm
func add x::number to::number:1 ::number = x + to
```

or 

```elm
func (add x::number to::number=1)::number = x + to
```

I propose the following:
```elm
func add = (x:number, to:number=1) : number => x + to
```
or
```elm
func add = (x:number, to:number=1) => x + to : number 
```
basically using the JS, Typescript `() => ...` syntax for functions. I think that very clearly and visually demonstrates that some values are used to produce a new value which should be understandable for newcomers.

**Comment by aljazerzen** [comment]
Let me lay a mental framework of how I think about the functions.

Functions are actually the core of the language, but remain hidden because of subtle syntax of the function call. Pipeline in PRQL means a series of functions and relational means that they operate on tabular data/tables/dataframes.

So when working on compiler I realized that pipeline transforms actually *are* normal functions, one could define as (using pseudo-Rust):
```rust
type Frame = HashMap<String, Vec<T>>

fn from(name: Ident) -> Frame {
	Frame { }
}

fn derive((alias, expr), frame: Frame) -> Frame {

	frame.alias = match expr {
		Ident(i) => frame[i],
		ScalarFunction(f(column)) => {
			frame.column.map(f)
		}
		VectorFunction(f(column)) => {
			f(frame.column)
		}
	}

	frame
}
	
fn aggregate((alias, expr), frame: Frame) -> Frame {
	new_frame = {}
	new_frame.alias = match expr {
		AggregationFunction(f(column)) => {
			[ f(frame.column) ]
		}
	}

	new_frame
}

fn multiply(factor: float, value: float) -> float {
	factor * value
}

fn sum(column: Vec<float>) -> float {
	column.iter().sum()
}

fn lag(column: Vec<float>) -> Vec<float> {
	column.insert_front(null)
	column.remove_back()
}
```

Now, pipeline is just a different notation of turning `foo(bar(x))` into `x | bar | foo`.

```elm
from employess
derive [
	net_salary: multiply 0.8 gross_salary
]
aggregate [
	total: sum net_salary
]
```
is equivalent to:
```rust
frame = from(employess)
frame = derive((net_salary, multiply(0.8)), frame)
frame = aggregate((total, sum()), frame)
```

Here `derive x` is a function call of function `derive` with one argument. Because `derive` expects two parameters, this call evaluates to a curry: a function that still expects one argument. This makes it possible to use this expression in a pipeline.

**Comment by aljazerzen** [comment]
I very strongly agree with "There should be one– and preferably only one –obvious way to do it." 

I see how it goes against currying and I do actually think that inline pipeline, currying and transform functions are all advanced features that should remain hidden for average user. To go even further I think that a linter should discourage use of single-function pipelines. This way, simple queries will almost never contain `|` symbol.

But for power-users, functional programming offers a well-defined and concise language. Such users are likely to be familiar with notion that `|` represents a pipe.

**Comment by snth** [comment]
So applying the previous suggestion to the examples from PR #442 in https://github.com/prql/prql/blob/99898cac610eff157dd65bc43e283f331703e729/reference/src/functions.md:

```elm
func (celsius_of_fahrenheit temp) = (temp - 32) * 3

from cities
derive temp_c = (celsius_of_fahrenheit temp_f)
```
becomes
```elm
func celsius_from_fahrenheit = (temp) => (temp - 32) * 3

from cities
derive [
  temp_c1 = temp_f >> celsius_from_fahrenheit,
  temp_c2 = celsius_from_fahrenheit(temp_f),
```

For functions with multiple parameters, I don't think it's always practical to have the main argument as the last parameter so I propose to use `_` as a placeholder to indicate which parameter should be substituted with the previous pipeline step when using the pipeline syntax.

So
```elm
func (interp lower=0 higher x) = (x - lower) / (higher - lower)

from students
derive [
  sat_proportion_1 = (interp 1600 sat_score),
  sat_proportion_2 = (interp lower=0 1600 sat_score),
]
```
becomes
```elm
func interp = (x, lower=0, higher) => (x - lower) / (higher - lower)

from students
derive [
  sat_proportion_1 = interp(sat_score, 0, 1600),
  sat_proportion_2 = sat_score >> interp(_, lower=0, 1600),
]
```

**Comment by aljazerzen** [comment]
Regarding function transforms: actually my function definition example was not entirely correct:
```diff
- func take_first col = (sort col | take 1)
+ func take_first col frame:Frame = (frame | sort col | take 1)
```

Your example would now produce a type error, because a call of `take_first` would be missing the frame argument.

Note that this is not meant for average user. It's the hidden tool that advanced used can leverage. It is also very logical production of how PRQL works.

It may seem that this makes PRQL unpredictable in its SQL output, but in essence, our functions are just macros - substitution of ident with an expression. It's just that in this case, use have a macro that substitutes frame transforms.

**Comment by aljazerzen** [comment]
> I propose the following:
> ```
> func add = (x:number, to:number=1) : number => x + to
> ```

Of course! `=>` is very obvious. I'm quite surprised we did not think of it before :D

What do you think about `->`? It's used in Java & Rust. 

Is there a reason for `=` after function name? I would prefer for function definition to be as close to function call, because that gives feeling of language consistency.

```elm
func add x:number to:number=1 => x + to
```

**Comment by snth** [comment]
https://github.com/prql/prql/issues/444#issuecomment-1115992366

Ok, having the `frame` parameter does make it clearer and alleviates my concern around that I think.

**Comment by snth** [comment]
https://github.com/prql/prql/issues/444#issuecomment-1116002602

No particularly strong feelings on `=>` vs `->`. I don't know Rust and JS has `=>` so that's what I went with. Happy with either.

```elm
func add x:number to:number=1 => x + to
```
I find the lack of parentheses and commas confusing to be honest. Like why are there no commas separating parameters because we have those everywhere else like in `[ , ]` expressions etc...?

To me having the `=` makes sense because if you think of functions as first-class objects then it's just another assignment to a name which just happens to have a function on the right hand side. I was initially going to propose doing away with the `func` and just have something like 
```elm
add = (x:number, to:number=1) => x + to
```
but I saw a comment from you somewhere that it's nice to have the `func` in the left column so one can just use that to scan for function definitions quickly so I kept it.

So I find the `=` makes sense because `add` and `(x:number, to:number=1) => x + to` are equal in that you should be able to use each interchangeably, so in my syntax the following should give the same results:
```elm
func add = (x, to=1) => x + to

from transactions
derive [
  total_1 = add(cost, markup),
  total_2 = ((x, to=1) => x + to)(cost, markup),
]
```

**Comment by aljazerzen** [comment]
Then let's rather use `->`, because ⇒ means implication in math.

----

Oh, that does make sense: everything has the syntax of lambda function.

@max-sixty wanted to have a language accessible to non-programmers, so he made function calls not use any punctuation. And that decision goes well with functional programming aspect of PRQL, because pipeline transforms have the same syntax.

With that in mind, what about:
```elm
func add = x to=1 -> x + to

from transactions
derive [
  total_1 = add cost markup,
  total_2 = cost markup | x to=1 -> x + to,
]
```
I've changed total_2 to inline pipeline, because function calls can only be parsed if they have ident as first term, preventing having a lambda function instead of function name.

But now, `cost markup` would be parsed as a function call... Ah. This no-punctuation rule is hard to keep consistent.

**Comment by max-sixty** [comment]
I sign off for a few hours and the PRQL has completely changed! Jokes aside, this is a good discussion, thank you.

---

> ```elm
> func add = x to=1 -> x + to
> ```

- This is interesting
- The punctuation between `add` and the arguments is reasonable and consistent with the rest of the language, even if it's not consistent with Ocaml, the original inspiration. 
- We do end up quite close to just doing a lambda:

  ```elm
  derive add = ([x, to=1] -> x + to)
  ```

  ...i.e. transform a list of args to an expression, and there's no need for `func`.

  I think there are reasons to not pursue this — lambda functions are much less helpful in PRQL than most languages, because all operations happen on arrays / columns already. We don't need to map `(x, y) => (x + 2y)` over a list, because PRQL & SQL already just accept `time + 2*overtime`, where `time` and `overtime` are arrays. So I think it's quite unlikely people will be using lambda functions inline.

- I'm not a great fan of using the `=` for both the `add =` and the `to=` — it's difficult to visualize where the break is. I think we should use it once there. And maybe use `:` for the other, like:
  ```
  func add = x to:1 -> x + to
  ```
  This would be consistent with having [aliases & assigns use different punctuation from named args](https://github.com/prql/prql/pull/442#issuecomment-1116762275)

- Maaaybe we need parentheses around `x to=1 -> x + to` to ensure the `->` binds tighter than the `=` in `func add =`?

---


> ```elm
> cost markup | x to=1 -> x + to,
> ```

Pipelines can never pass more than value (at least how I'm thinking about them). They can pass tuples, but I don't think we need that language feature.

---

Re `=>` vs `->`: no strong view — IIRC JS does `=>` and Java does `->`. Rust only uses `->` in the type definition.

---

While roundly condemned [last time I brought it up](https://github.com/prql/prql/issues/300#issuecomment-1102110603), indentation would work!

```elm
func add x y
  x + y
```

```elm
func lag_day x
  group sec_id
    sort date
    window
      lag 1 x
```

(ok ok, I'll try not to bring it up again)

---

> I very strongly agree with "There should be one– and preferably only one –obvious way to do it."
> 
> I see how it goes against currying and I do actually think that inline pipeline, currying and transform functions are all advanced features that should remain hidden for average user. To go even further I think that a linter should discourage use of single-function pipelines. This way, simple queries will almost never contain `|` symbol.
> 
> But for power-users, functional programming offers a well-defined and concise language. Such users are likely to be familiar with notion that `|` represents a pipe.

100% agree with @aljazerzen here + his previous comment

**Comment by max-sixty** [comment]
Trying to add things up into some options across this & https://github.com/prql/prql/issues/444 (though good idea to keep them as separate issues originally), some broad clusters of options:

1. Status quo — don't change anything, use `::` for annotations
   ```elm
   func::number interp lower:0 higher x::number = (x - lower) / (higher - lower)

   from s:students
   derive [
     sat_proportion_1: (interp 1600 sat_score),
     sat_proportion_2: (interp lower:0 1600 sat_score),
   ]
   ```
1. Use `:` for Named args, `=` for Aliases & Assigns, `::` for annotations:
   Note that we can dispense with the parentheses in the derive for this & the next couple.
   ```elm
   func::number interp = lower:0 higher x::number -> (x - lower) / (higher - lower) 

   from s=students
   derive [
     sat_proportion_1 = interp 1600 sat_score,
     sat_proportion_2 = interp lower:0 1600 sat_score,
   ]
   ```
1. Use `=` for Named args, `=` for Aliases & Assigns, `::` for annotations:
   ```elm
   func::number interp = lower:0 higher x::number -> (x - lower) / (higher - lower)

   from s=students
   derive [
     sat_proportion_1 = interp 1600 sat_score,
     sat_proportion_2 = interp lower:0 1600 sat_score,
   ]
   ```
1. I'm going to put one more out there — use `<>` for types. They are used for generic in Rust, but `impl Point<i32>` is correct and similar to what we're doing, and lets us use `:` more clearly for other things.
   Use `:` for Named args, `=` for Aliases & Assigns, `<>` for annotations:
   ```elm
   func<number> interp = lower:0 higher x<number> -> (x - lower) / (higher - lower)

   from s=students
   derive [
     sat_proportion_1 = interp 1600 sat_score,
     sat_proportion_2 = interp lower:0 1600 sat_score,
   ]
   ```

(We don't need to define `=>` vs `->` / parentheses around funcs / `=` after func name / arguments-as-lists, etc here — this is for the issues where we face tradeoffs between different threads)

As you look through, weigh the main query 5x higher than the func, and the func 5x higher than the type annotations!

**Comment by max-sixty** [comment]
Just to follow-up on this:

> @max-sixty wanted to have a language accessible to non-programmers, so he made function calls not use any punctuation. And that decision goes well with functional programming aspect of PRQL, because pipeline transforms have the same syntax.

Right — general purpose languages have lots of punctuation, because they need lots of widgets — lists & tuples & sets & dicts. The two types of languages without lots of punctuation:
- Functional languages like Ocaml, where the language is very small and most things are implementations
- DSLs like SQL, which have limited semantics

So I envisage PRQL as a DSL for analytical queries — centering around the notion of a pipeline, removing SQL's warts, adding functions & variables, and keeping features like bare words (`select foo` rather than `select "foo"`). And so appealing both to 1) advanced users who miss basic features, tire of the warts, and have seen languages which don't need to be complicated, and 2) beginners who don't want to learn lots of punctuation[^1].

One piece of feedback I'm open to is: not having as much punctuation makes it _more_ complicated to read or learn. But it's important not to have that as a first reaction only because it's different from Python & Java. So I would want to hear what people like @aljazerzen think, who has spent a lot of time writing the lang.

[^1]: e.g. for a toy example: why do python functions need colons at the end?

Check out [Ocaml functions](https://cs3110.github.io/textbook/chapters/basics/functions.html) for more (and [labeled arguments](https://v2.ocaml.org/manual/lablexamples.html) too!)

**Comment by aljazerzen** [comment]
### Function calls and pipeline

After some thinking, I concluded that we must keep pipeline transforms' syntax the same as normal function calls for consistency, much simpler compiler. This limits us with syntax on lambda functions, but as @max-sixty pointed out, they are not really needed in this language, because expressions of select and derive are already treated as functions applied to the whole column.

### Equals

I've persuaded that conceptually, named args, assigns and equality comparisons are different things and should hence have different syntax. Python confuses this a bit with their named args. So this crosses out options 1. and 3.

I would also avoid 4., because `<>` may be needed for generic types: `func sum col::column<number> -> ...`

This leaves option 2. The most important part here - the query - indeed looks the most readable of all options to me to me:
```elm
derive [
  sat_proportion_1 = interp 1600 sat_score,
  sat_proportion_2 = interp lower:0 1600 sat_score,
]
```

(about scoping with indentation: I would still avoid it)

**Comment by qharlie** [comment]
2 gets my vote!

**Comment by snth** [comment]
I agree that the most readable option is

2. Use `:` for Named args, `=` for Aliases & Assigns, `::` for annotation

so Named Args get a different symbol from Aliases and Assigns.

Just one idea (since I'm not shy about throwing wacky ones out there), what about `~` for Named Args, that way we could still keep `:` for annotations?

So instead of

```elm
func::number interp = lower:0 higher x::number -> (x - lower) / (higher - lower) 
```
have 
```elm
func:number interp = lower~0 higher x:number -> (x - lower) / (higher - lower) 
```

I'm not aware of `:` being used for named args in (m)any languages so we wouldn't be going against an established convention and this would allow us to keep with the convention of having `:` for type annotations.

One use of `~` is for "distributed as" in statistics (e.g. `X~N(0,1)`) so here we would just have the parameter distributed according to a singleton distribution of the default value. Anyway, it's a bit of a stretch I know but it would be nice to keep the `:` annotations as I find the `::` introduces a bit of line noise.

**Comment by snth** [comment]
https://github.com/prql/prql/issues/444#issuecomment-1116910865

Thanks. I had a look at [OCaml functions](https://cs3110.github.io/textbook/chapters/basics/functions.html) because I don't know OCaml at all.

In 2.4.2 he writes

> We now have two ways we could write an increment function:
> 
> ```ocaml
> let inc x = x + 1
> let inc = fun x -> x + 1
> ```

It seems that the function syntax we have arrived at is very close to the second form (apart from moving the `fun(c)` token to the front and not requiring this be in a let/derive block).

I feel quite strongly that the first form is not very intuitive to beginners and should not be supported in PRQL. There is nothing inherent in the notation to suggest that the first name is the name of the function and the remaining names are the names of parameters.

I agree that lambdas/anonymous functions are probably not going to play a big role in PRQL but I think the syntax quite intuitively communicates that you are dealing with a mapping.

One case where I think lambdas could come up is when trying to apply transformations, so if we have a rule that function transformation always apply to the last or first parameter then you might want to define a lambda just ahead of that to move the parameter you are interested in, into the required position (if you can't specify it otherwise). Not sure if that scenario would really ever come up but it's the main case I could think of.

While on the OCaml syntax, in section 2.4.6 of that link, he says

> Here are two equivalent ways of squaring 6:
> 
> ```ocaml
> square (inc 5);;
> 5 |> inc |> square;;
> ```

So OCaml uses `|>` for the pipeline operator. As mentioned elsewhere, I'm not a fan of the `|` for the pipeline operator and would prefer something like `|>` or `>>` which gives a visual indication of the data flow similar to the `%>%` in dplyr and R.

**Comment by qharlie** [comment]
> (since I'm not shy about throwing wacky ones out there)

Yeah keep 'em coming!

We did talk about `~` , using it for derives and aliases because of it's use to mean approximate, but in the end the `:` won out.

> So OCaml uses |> for the pipeline operator. As mentioned elsewhere, I'm not a fan of the | for the pipeline operator and would prefer something like |> or >>

I'm going to go out on a limb here and say _I dont like this method of function calling_. 

I love having the transformations piped into one another, and it makes logical sense to support them for functions, but I think it's confusing when reading the query.  I can envision half of the people will use this everywhere, and the other half won't use it all, splitting PRQL users into two camps.

**Comment by snth** [comment]
Just thought I would look at what are some expressions in my code and how would those look in PRQL.

How would I best write the following?
```sql
ABS(COALESCE(a.amount, 0) - COALESCE(b.amount, 0)) AS difference
```

Like this?
```elm
derive difference = abs ((coalesce a.amount 0) - (coalesce b.amount 0))
```
As a non-lisper this has the parentheses the wrong way around to my eye.

```elm
derive difference = (coalesce a.amount 0) - (coalesce b.amount 0) | abs
```
This allows us to remove one layer of parentheses but as @charlie-sanders commented, will probably look unfamiliar to most people at first. I think one might get used to it though. I'm not sure how tightly the function application binds and whether you would get away with the following (and whether that aids readability and you'd want to)?
```elm
derive difference = coalesce a.amount 0 - coalesce b.amount 0 | abs
```
Actually, seeing it written out the above doesn't look too bad!

I also thought of doing this via lambdas:
```elm
derive [
    null2zero = x -> coalesce x 0,
    absdiff1 = a b -> abs (null2zero a - null2zero b),
    absdiff2 = a b -> null2zero a - null2zero b | abs,
    difference = absdiff2 a.amount b.amount,
]
```

**Comment by aljazerzen** [comment]
Again, just documenting current state of the language.

Currently, operator precedence is as follows:

- unary operators
- multiplication / division
- addition / subtraction
- comparisons
- logical operators (and, or)
- function calls

Function call is an ident, followed by any number of expressions.

> Example:
> ```
> foo -hello + 2 bar find 5 + age / 2 < 10 and is_single
> ```
> is a function call of `foo`, with args:
> - `(-hello) + 2`
> - `bar`
> - `find`
> - `( (5 + (age / 2)) < 10 ) and is_single`

There is also a rule that a function argument cannot be direct function call:

> ```
> foo bar sum salary 5
> ...is same as
> foo (bar) (sum) (salary) (5)
> ...but different from
> foo (bar) (sum salary 5)
> ```

So your example can be written as:
```
derive difference = abs (coalesce a.amount 0) - (coalesce b.amount 0)
```
but without all parenthesis it would mean:
```
derive difference = abs (coalesce) (a.amount) (0 - coalesce) (b.amount) (0)
```

This precedence has been adapted from MS SQL and Postgres and is such so that `abs length - 5` is interpreted as `abs (length - 5)`.

-------

To be honest I don't like mixing frame columns and function definitions. From:
```elm
select [
    null2zero = x -> coalesce x 0,
    absdiff1 = a b -> abs (null2zero a - null2zero b),
    absdiff2 = a b -> null2zero a - null2zero b | abs,
    difference = absdiff2 a.amount b.amount,
]
```
... one may figure that there are 4 columns in the frame, while in truth there is only one. This may not be obvious, because of currying, which is only a logical consequence in a function language:
```
select [
  add = a b -> a + b
  add_one = add 1
  age_next_year = add_one age
]
```

------

Instead, I am for less-lambda-oriented function definition:

```
func absdiff1 a b:1 -> abs (null2zero a - null2zero b)
```
Because we agreed that named arguments use `:`, we don't need any parenthesis and can even drop `->`:

```elm
func absdiff1 a b:1 = abs (null2zero a - null2zero b)
```
I'm fine with either of these. I'm not sure where to put types of the return value though. After the function name?

**Comment by max-sixty** [comment]
Agree with @aljazerzen above!

---

To ensure we balance being open to changes while focusing the discussion on the areas most likely to lead to productive changes — to change the `|` syntax to `>>` or `|>`, we would need cases where it's better, and given it's a simple swap — and for an additional character of such a fundamental language — I think that would be a challenge.

I would weigh cases far above our intuition of what looks better in the abstract — cases give us a shared legible understanding which we can build on. And I'm including my own intuition here when I say it should come below cases.

**Comment by aljazerzen** [comment]
Working on compiler: it's easier to have `->` instead of `=` in current parser implementation.

-----

Regarding pipes: because this is quite fundamental part of the language I would avoid `|>` just because is harder to type than alternatives. I'm fine with both `|` and `>>`.

**Comment by snth** [comment]
Regarding the pipes: I also don't like `|>` and just suggested it because of the OCaml references. 
@max-sixty I agree with your point about weighing cases higher than abstract reasoning. From my examples above and the return index example in the Readme.md, I have to say the `|` looks fine and I have come around to that side.

---

Thanks for the function syntax clarifications @aljazerzen . I had read through the syntax and functions pages on [https://lang.prql.builders/]() but didn't see anything about this before.

Is the low precedence for function calls the common convention for functional languages? I must say I find those examples you posted impossible to read. 

Comparing
```elm
foo -hello + 2 bar find 5 + age / 2 < 10 and is_single
```
with the usual parentheses based function invocation
```elm
foo(-hello + 2, bar, find, 5 + age / 2 < 10 and is_single)
```
, at least in the latter a novice can find their way around with high school math.

Not saying that anyone would write code like that but given that someone might be able to seems like a bit of a concern to me because advanced users can write queries that beginners won't be able to understand. SQL kinda forces you to ride your bike with the training wheels on, which while frustrating to us, does keep it accessible. That said the examples in the Readme file read great. Perhaps it's another case of worrying too much about things in the abstract without concrete examples to back it up.

I just think that keeping the language accessible to novice programmers would be quite key. I deal with quite a lot of Data Analysts for example who only really have Excel experience and for SQL is the next step up. I don't see them ever groking those function application rules but maybe I'm wrong.

Anyway, I've been throwing out a lot of comments and suggestions and don't want to take up too much of your bandwidth. IMHO keeping the language simple would probably help with wider adoption but that's just a hunch. I want to get myself set up to start using PRQL for some of my data work to get a feel for it in practice and then comment from that perspective rather than arguing in the abstract.

**Comment by aljazerzen** [comment]
That is true - the example is not readable at all. But thats an extreme example - most functions have only one or two params that are pretty obvious.

Regarding the clarifications, they are fresh from the compiler :D They should eventually make it to the reference book, but I really don't like writing documentation. Can someone help here?

I also agree that we should postpone this discussion after we generated more examples and used PRQL in practice.

Yesterday I was working on the compiler I was changing assigns to `=`. During that process I found out that having `->` for functions makes parsing quite easier, so I've also changed that. This means that now compiler uses my the last proposed syntax. But that is not a final decision, this issue will remain open.

**Comment by max-sixty** [comment]
> Regarding the clarifications, they are fresh from the compiler :D They should eventually make it to the reference book, but I really don't like writing documentation. Can someone help here?

Yeah, docs aren't my favorite but happy to take this one given our relative contributions over the past couple of weeks!

**Comment by max-sixty** [comment]
Thanks to everyone for the discussion and to @aljazerzen for the implementation. I'm v happy about the place we're in. I'll close this GH issue. I'll do some work on the associated docs.

(though it doesn't mean the _topic_ is closed — feel free to either reopen this or open a new issue, CC @snth)
