### ISSUE TITLE
Tag line

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#458]
In conversations with people, they really like the concept of a pipeline — which is convenient given our focus.

The tag line is currently, in bold:

- **PRQL is a modern language for transforming data — a simpler and more powerful SQL.** Like SQL, it's readable, explicit and declarative. Unlike SQL, it forms a logical pipeline of transformations, and supports abstractions such as variables and functions. It can be used with any database that uses SQL, since it transpiles to SQL.

I think it's decent — it's conveys both the broad goal a a way of linking it to what people know. Can we stress the pipeline aspect more?

A couple of options:

- **PRQL is a modern pipeline language for transforming data — a simpler and more powerful SQL.** [...]

- **PRQL is a modern language for transforming data with pipelines — a simpler and more powerful SQL.** [...]

- **PRQL is a modern language for transforming data — a simpler and more powerful SQL.** PRQL queries are a pipeline of transformations. 

And possibly change the last part:
```diff
Like SQL, it's readable, explicit and declarative. 
-Unlike SQL, it forms a logical pipeline of transformations, 
+Unlike SQL, it's composed of a coherent set of transformations,
and supports abstractions such as variables and functions. 
-It can be used with any database that uses SQL, since it transpiles to SQL.
+It can be used with any database that uses SQL, since it compiles to SQL.
```

(I've tried to avoid the word "orthogonal" despite the urge)

**Comment by qharlie** [comment]
I'm loving the original honestly, it's a great tag line.

**Comment by aljazerzen** [comment]
I agree that we should avoid "orthogonal", because it may not be understood without seeing the language.

----

I see the tag line is answering two questions:
- what this is? - **PRQL is a modern language for transforming data**
- how does it compare to SQL? - **a simpler and more powerful SQL**

I think that we should add "pipelined" to the comparison with SQL, because this is the main improvement when replacing SQL. 

Am I correct in assuming that:
- "simpler" is referring to "only one way of doing things" and "orthogonal" transforms, and
- "more powerful" is referring to ranges, dates, and other such features?

If so, I propose: **a simpler and empowered pipelined SQL**

----

What I think is missing, is comparison to other data transformation tools: DataFrame libraries and spreadsheets. Something like:
- how does it compare to pandas/dplyr? - **a unified and consistent interface for querying data frames**
- how does it compare to Excel? - **a reproducible pipeline of spreadsheets**

I am not sure:
- how would be fit all comparisons together,
- if we even need them and
- if I'm hitting our intentions (especially for the Excel).

**Comment by snth** [comment]
I think it's great and hard to improve upon.

---
* **PRQL is a modern language for transforming data** 
To me this is the most general statement. If we look at where we fit in the ETL or ELT stack, we are really addressing the **T**ransform part so I think it is great as it stands. Even going beyond to where we are going with the Jupyter, JS, ... integrations, transforming data is really the key aspect.

---
* Unlike SQL, it forms a **logical pipeline of transformations**
This seems like a good place to introduce the pipeline concept as it expands on the data transformations part and explains how those are structured. I wouldn't change that part.

**Comment by aljazerzen** [comment]
Reviewing this: we decided to add reference to DataFrames and spreadsheets at a later time.

Currently, we are only adding "pipelined" to the line.

**Comment by max-sixty** [comment]
Great, agree. I'm happy to make the change
