### ISSUE TITLE
Source highlight.js externally

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#577]
Currently we have a big JS file — highlight.js — which is copied into the repo so we can use a more recent version of highlight.js.

Is this required, or can we point an a version hosted elsewhere (e.g. a CDN)? I'm not sure how external imports work in JS. Currently it's responsible for 1/3 of the LOC in the repo.

**Comment by aljazerzen** [comment]
Do you mean reference book or the website?
- mdbook already includes highlight.js by default, there is no need for have it ourselves (edit: oh I see, we want a recent version)
- website also has highlight.min.js commited as an asset.

Ideally, this should be handled by a dependency manager, npm in this case. But because we currently don't have npm present in the build process of neither of the sites, I don't think it's worth adding.

As for CDNs, I really dislike them, because the main argument for their usage - shared resources between sites - no longer applies, because modern browsers cache resources for each hostname separately. Arguably, they may make the sites load slower, because a new TCP + TLS connection has to be opened to load the resources instead of just using existing connection to the website.

So my opinion is to either:
- move site themes into their own repo where there is no problem having highlight.js committed. Hugo advises this by default, so the theme can be reused for other websites.
- just keep them here, as is. I'm not bothered by extra 152 KB in the repo. We could minify it, though.

**Comment by max-sixty** [comment]
Minifying is great, I did this for both, and we're now back to being a majority-rust repo! Thanks!
