### ISSUE TITLE
Emphasis of code on website is too severe

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#620]
I find the orange-on-black too strong, such that it's difficult to read a sentence with code in:

<img width="960" alt="image" src="https://user-images.githubusercontent.com/5635139/174722419-3ed424a1-253e-42e7-9e3f-f5c1a8e60965.png">

Does anyone else share this?

**Comment by max-sixty** [comment]
The FAQ is quite the aesthetic rollercoaster:

<img width="1340" alt="image" src="https://user-images.githubusercontent.com/5635139/174724783-412a85db-b5f2-4832-a858-aa206ad14bbf.png">

**Comment by roG0d** [comment]
Is this something more appeal for reading? I've tried to stick with the markdown `standard block code` but a little bit darker in order to read properly the prql/sql code blocks

![Captura de pantalla_2022-06-21_14-12-37](https://user-images.githubusercontent.com/32329949/174796348-86169f75-6aab-43bc-ada4-50099954a456.png)

**Comment by max-sixty** [comment]
That is better much for the inline code snippets. 
I'm no UI designer but maybe the inline could be in light mode; maybe there's too much difference when doing dark mode?

I think if we're going to have the full code blocks be in dark mode, then the existing approach was OK — it maybe looks a bit washed out with the colors on the gray-ish background?
(We could try light mode for those too, but your call)

**Comment by max-sixty** [comment]
This was closed by @aljazerzen
