### ISSUE TITLE
Change Footer to a "Contribute" / "Join us" section?

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#623]
Should this be another section on the homepage, rather than in the footer?

<img width="1368" alt="image" src="https://user-images.githubusercontent.com/5635139/174723758-55e0e703-5b16-4f87-ba3b-fc59226ae733.png">

**Comment by roG0d** [comment]
In my humble opinion, I think it has a very good place for everyone to see it! it's just at the very end when people are finished reading the homepage.

It's true that if we have a section for the contributions we could add more information. But I think it will overload the homepage. Maybe it's better to create a new page and link it to the header.

That said, I think it's a pretty decent place! because what could we put there on the footer otherwise?

**Comment by max-sixty** [comment]
OK great. And @aljazerzen do you agree? Let's close this issue if so.

**Comment by aljazerzen** [comment]
Yup, i agree
