### ISSUE TITLE
Pipeline of functions from PRQL to SQL

### ISSUE THREAD

**Issue by max-sixty** [PRQL/prql#759]
(To preface, this isn't intended as a criticism of the amazing work that's been done on the compiler (CC @aljazerzen !). I realize this goal isn't easy, and there's a tradeoff around efficiency and modularity.)

It would be great to have a set of modular functions that take an object and return an object, going from PRQL to SQL when strung together; something like:
- Parse from PRQL string to PRQL AST (via a parse tree)
- Materialize functions & variables, check types, etc — some amount of "lowering" — needs more definition
- Translate into SQL AST
- Display into SQL string
- Format into formatted SQL string

As a case — when working on https://github.com/prql/prql/pull/752, I couldn't find a way of seeing the SQL AST easily, because `resolve_and_translate` outputs a string, and `translate` requires a context parameter.

Maybe this is as easy as making a default `Context` object so we can easily access the intermediate functions. Some of it is also documenting the pipeline, and letting people less familiar with the current process get started quickly. We could also have a test process which takes a PRQL query and snapshot-tests each stage — currently we somewhat do this implicitly by adding the same expression to tests to `parser.rs` and `translator.rs` — and we could formalize this and probably reduce the number of tests.

**Comment by aljazerzen** [comment]
Lately, I've seen a few questions about `to_ast` function and using Substrait.io as a backend and I've realized that we need an "intermediate representation".

Current to_ast does provide this to some extent, but there is no way of converting this back to a PRQL or SQL query. Instead, I propose we start thinking about this IR as a *resolved, type checked and materialized* query plan:

```
     PRQL
      |  ^
parse |  | fmt
      v  |
     AST
      | 
      | semantic analysis & materialization
      v
     IR (serializable as JSON or protobuf in the future)
      |
      | translate
      +----------+----------+
      |          |          |
      v          v          v
     SQL      Polars     Substrait
```

IR should be equivalent to Substrait's query plan and I'm thinking that maybe we could exactly model their schema, but I haven't inspected it enough to see if that would be possible.

But the caveat is that IR should have a standard form regardless of the dialect. This means that prior to `translate`, we should not materialize functions that use s-strings to refer to DBMS's functions, since they may depend on the query engine. So when compiling directly to SQL, IR would contain something like `aggregate [new_column = <std::sum> old_column]` and only the translator would know how to finally materialize `std::sum` in appropriate dialect.

-----

Anyway, I'm not quite sure on having this IR in architecture yet, but it's on the topic of how to structure the major compiler functions you are talking about.

On that topic:
- yes, `Context` should be hidden from the outside of `semantic` modules. I already did some work on that front in the draft of the type-checking PR
- I also agree that many tests could be de-duplicated by applying them to each of the stages.
