### ISSUE TITLE
I love this XD

### ISSUE THREAD

**Issue by kokizzu** [PRQL/prql#8]
a bit similar with what I thought for a while
https://www.reddit.com/r/Database/comments/qe0jwk/why_sql_why/

**Comment by biels** [comment]
Was looking for this issue, otherwise I would have created it myslef :)

Hope this project has a bright future. And **please make it compile to SQL**, not a complete separate interpreter, runtime and so on. It should be used work with PostgreSQL for example. ORMs and similar projects can then be based on this as a primitive to be simpler and offer it as an escape hatch for complex queries.

**Comment by max-sixty** [comment]
Thanks a lot for the well-wishes! The last nine months have flown by.

I'm cleaning up issues, so I will close this, but appreciate the sentiment and please keep in touch with the project through GH / Discord / Twitter / etc.
