### ISSUE TITLE
How to integrate and use in the rust project? Is there a quick start for different languages?

### ISSUE THREAD

**Issue by songlinshu** [PRQL/prql#828]
HI,How to integrate and use in the rust project? Is there a quick start for different languages?

**Comment by max-sixty** [comment]
Hi @songlinshu — the question at the top of https://prql-lang.org/faq/ might be applicable.

Otherwise could you help us understand what you're trying to do? If you want to start using PRQL for you queries, those two integrations are the easiest way. If you want to build an app on top of PRQL, then you want the language bindings.

If you just want to experiment, there's a playground: https://prql-lang.org/playground/

**Comment by qharlie** [comment]
I've made a new task for creating a Rust getting-started example if that was the original intent ;)

**Comment by max-sixty** [comment]
I'll close this for the moment, but please feel free to ask questions, and we'll add anything that's missing into docs.
