### ISSUE TITLE
Filter by list of strings

### ISSUE THREAD

**Issue by blackary** [PRQL/prql#900]
Is it possible to do something like the following to generate `where name in ("david", "george", "sam")`?

```
from table
filter name in ["david", "george", "sam"]
```

I tried a few different potential versions of the syntax, and none of them seemed to work, and couldn't find this documented in the book.

**Comment by max-sixty** [comment]
We'd like to do this — https://github.com/prql/prql/issues/747

It requires some changes in the compiler so we can use `in` for both `between` and "contained in list" depending on the type. If someone wanted to add it in rust code rather than the stdlib, I think that wouldn't be too difficult; though would be temporary code.

If it's OK @blackary, I'll close this in favor of #747

**Comment by blackary** [comment]
@max-sixty Yes, that's great. I hadn't seen that issue.
