### ISSUE TITLE
About Handling of NULL

### ISSUE THREAD

**Issue by shota-kizawa** [PRQL/prql#99]
If this has already been discussed somewhere and a conclusion has been reached, please close.

When representing that a column is null, the

- IS NULL
- = null
- Other

Which one do you use?

**Comment by shota-kizawa** [comment]
For a SQL user
```
filter column IS NULL
```
is easier to understand. (I also think it's easier to understand because I can express that NULL is special.)
However, it is possible to use.
```
filter column = null
```
It's simpler because you don't have to use the IS operator.

**Comment by max-sixty** [comment]
The null handling in SQL can be quite confusing. I'm open to thoughts on changing how we do comparisons. 

One problem with a `filter column = null` in PRQL compiling to `column is null` in SQL:  in SQL, `column = null` is allowed, even if it's probably a mistake. So there wouldn't be a way to represent `column = null` in SQL.

I'm up for suggestions though. Without them, we'll probably just default to SQL representation of these initially.

---

While you raise the general topic — unfortunately we probably can't do anything about SQL's overall handling of nulls, since it's an issue with how DBs handle nulls, rather than an issue with the language.

**Comment by aljazerzen** [comment]
I think that if `column = NULL` is always evaluated to false (or null), there is no need for PRQL to be able to express it. Therefore, we can convert `column = null` into `column IS NULL`.

One step further, we can even ban `IS` operator from PRQL, because it is only applicable for `IS TRUE` `IS FALSE` `IS NULL` and `IS UNKNOWN` ([see postgres docs](https://www.postgresql.org/docs/9.0/functions-comparison.html)). These can all be written using `=` operator, if we transpile as written above.

This way, language has less sharp corners and is more consistent. SQL was designed a long time ago and some things (like NULL not being a value or UNKNOWN keyword) did not stand the test of time, which is why we can remove them, without worrying about backward compatibility, as SQL has to.
